// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
	"net/http"
)

type GetDataplaneInsightRequest struct {
	// name of the mesh
	Mesh string `pathParam:"style=simple,explode=false,name=mesh"`
	// name of the DataplaneInsight
	Name string `pathParam:"style=simple,explode=false,name=name"`
}

func (g *GetDataplaneInsightRequest) GetMesh() string {
	if g == nil {
		return ""
	}
	return g.Mesh
}

func (g *GetDataplaneInsightRequest) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

type GetDataplaneInsightResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	DataplaneInsightItem *shared.DataplaneInsightItem
	// Not Found
	NotFoundError *shared.NotFoundError
}

func (g *GetDataplaneInsightResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetDataplaneInsightResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetDataplaneInsightResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetDataplaneInsightResponse) GetDataplaneInsightItem() *shared.DataplaneInsightItem {
	if g == nil {
		return nil
	}
	return g.DataplaneInsightItem
}

func (g *GetDataplaneInsightResponse) GetNotFoundError() *shared.NotFoundError {
	if g == nil {
		return nil
	}
	return g.NotFoundError
}
