// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
	"net/http"
)

type GetGlobalSecretRequest struct {
	// name of the GlobalSecret
	Name string `pathParam:"style=simple,explode=false,name=name"`
}

func (g *GetGlobalSecretRequest) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

type GetGlobalSecretResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	GlobalSecretItem *shared.GlobalSecretItem
	// Not Found
	NotFoundError *shared.NotFoundError
}

func (g *GetGlobalSecretResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetGlobalSecretResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetGlobalSecretResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetGlobalSecretResponse) GetGlobalSecretItem() *shared.GlobalSecretItem {
	if g == nil {
		return nil
	}
	return g.GlobalSecretItem
}

func (g *GetGlobalSecretResponse) GetNotFoundError() *shared.NotFoundError {
	if g == nil {
		return nil
	}
	return g.NotFoundError
}
