// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/internal/utils"
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
	"net/http"
)

// GetMeshTraceListAllMeshesQueryParamFilter - filter by labels when multiple filters are present, they are ANDed
type GetMeshTraceListAllMeshesQueryParamFilter struct {
	Key   *string `queryParam:"name=key"`
	Value *string `queryParam:"name=value"`
}

func (g *GetMeshTraceListAllMeshesQueryParamFilter) GetKey() *string {
	if g == nil {
		return nil
	}
	return g.Key
}

func (g *GetMeshTraceListAllMeshesQueryParamFilter) GetValue() *string {
	if g == nil {
		return nil
	}
	return g.Value
}

type GetMeshTraceListAllMeshesRequest struct {
	// offset in the list of entities
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
	// the number of items per page
	Size *int64 `default:"100" queryParam:"style=form,explode=true,name=size"`
	// filter by labels when multiple filters are present, they are ANDed
	Filter *GetMeshTraceListAllMeshesQueryParamFilter `queryParam:"style=form,explode=true,name=filter"`
}

func (g GetMeshTraceListAllMeshesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMeshTraceListAllMeshesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetMeshTraceListAllMeshesRequest) GetOffset() *int64 {
	if g == nil {
		return nil
	}
	return g.Offset
}

func (g *GetMeshTraceListAllMeshesRequest) GetSize() *int64 {
	if g == nil {
		return nil
	}
	return g.Size
}

func (g *GetMeshTraceListAllMeshesRequest) GetFilter() *GetMeshTraceListAllMeshesQueryParamFilter {
	if g == nil {
		return nil
	}
	return g.Filter
}

type GetMeshTraceListAllMeshesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List
	MeshTraceList *shared.MeshTraceList
}

func (g *GetMeshTraceListAllMeshesResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetMeshTraceListAllMeshesResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetMeshTraceListAllMeshesResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetMeshTraceListAllMeshesResponse) GetMeshTraceList() *shared.MeshTraceList {
	if g == nil {
		return nil
	}
	return g.MeshTraceList
}
