// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
	"net/http"
)

type GetMeshInsightRequest struct {
	// The name of the mesh to get the insight for.
	Name string `pathParam:"style=simple,explode=false,name=name"`
}

func (g *GetMeshInsightRequest) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

type GetMeshInsightResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// A response containing the insight of a mesh.
	MeshInsightWithMeta *shared.MeshInsightWithMeta
	// Bad Request
	BadRequestError *shared.BadRequestError
	// Not Found
	NotFoundError *shared.NotFoundError
	// Internal
	InternalError *shared.InternalError
}

func (g *GetMeshInsightResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetMeshInsightResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetMeshInsightResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetMeshInsightResponse) GetMeshInsightWithMeta() *shared.MeshInsightWithMeta {
	if g == nil {
		return nil
	}
	return g.MeshInsightWithMeta
}

func (g *GetMeshInsightResponse) GetBadRequestError() *shared.BadRequestError {
	if g == nil {
		return nil
	}
	return g.BadRequestError
}

func (g *GetMeshInsightResponse) GetNotFoundError() *shared.NotFoundError {
	if g == nil {
		return nil
	}
	return g.NotFoundError
}

func (g *GetMeshInsightResponse) GetInternalError() *shared.InternalError {
	if g == nil {
		return nil
	}
	return g.InternalError
}
