// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/internal/utils"
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
	"net/http"
)

// GetMeshTrustListAllMeshesQueryParamFilter - filter by labels when multiple filters are present, they are ANDed
type GetMeshTrustListAllMeshesQueryParamFilter struct {
	Key   *string `queryParam:"name=key"`
	Value *string `queryParam:"name=value"`
}

func (g *GetMeshTrustListAllMeshesQueryParamFilter) GetKey() *string {
	if g == nil {
		return nil
	}
	return g.Key
}

func (g *GetMeshTrustListAllMeshesQueryParamFilter) GetValue() *string {
	if g == nil {
		return nil
	}
	return g.Value
}

type GetMeshTrustListAllMeshesRequest struct {
	// offset in the list of entities
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
	// the number of items per page
	Size *int64 `default:"100" queryParam:"style=form,explode=true,name=size"`
	// filter by labels when multiple filters are present, they are ANDed
	Filter *GetMeshTrustListAllMeshesQueryParamFilter `queryParam:"style=form,explode=true,name=filter"`
}

func (g GetMeshTrustListAllMeshesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMeshTrustListAllMeshesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetMeshTrustListAllMeshesRequest) GetOffset() *int64 {
	if g == nil {
		return nil
	}
	return g.Offset
}

func (g *GetMeshTrustListAllMeshesRequest) GetSize() *int64 {
	if g == nil {
		return nil
	}
	return g.Size
}

func (g *GetMeshTrustListAllMeshesRequest) GetFilter() *GetMeshTrustListAllMeshesQueryParamFilter {
	if g == nil {
		return nil
	}
	return g.Filter
}

type GetMeshTrustListAllMeshesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List
	MeshTrustList *shared.MeshTrustList
}

func (g *GetMeshTrustListAllMeshesResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetMeshTrustListAllMeshesResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetMeshTrustListAllMeshesResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetMeshTrustListAllMeshesResponse) GetMeshTrustList() *shared.MeshTrustList {
	if g == nil {
		return nil
	}
	return g.MeshTrustList
}
