// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/internal/utils"
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
	"net/http"
)

// GetMeshZoneAddressListAllMeshesQueryParamFilter - filter by labels when multiple filters are present, they are ANDed
type GetMeshZoneAddressListAllMeshesQueryParamFilter struct {
	Key   *string `queryParam:"name=key"`
	Value *string `queryParam:"name=value"`
}

func (g *GetMeshZoneAddressListAllMeshesQueryParamFilter) GetKey() *string {
	if g == nil {
		return nil
	}
	return g.Key
}

func (g *GetMeshZoneAddressListAllMeshesQueryParamFilter) GetValue() *string {
	if g == nil {
		return nil
	}
	return g.Value
}

type GetMeshZoneAddressListAllMeshesRequest struct {
	// offset in the list of entities
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
	// the number of items per page
	Size *int64 `default:"100" queryParam:"style=form,explode=true,name=size"`
	// filter by labels when multiple filters are present, they are ANDed
	Filter *GetMeshZoneAddressListAllMeshesQueryParamFilter `queryParam:"style=form,explode=true,name=filter"`
}

func (g GetMeshZoneAddressListAllMeshesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMeshZoneAddressListAllMeshesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetMeshZoneAddressListAllMeshesRequest) GetOffset() *int64 {
	if g == nil {
		return nil
	}
	return g.Offset
}

func (g *GetMeshZoneAddressListAllMeshesRequest) GetSize() *int64 {
	if g == nil {
		return nil
	}
	return g.Size
}

func (g *GetMeshZoneAddressListAllMeshesRequest) GetFilter() *GetMeshZoneAddressListAllMeshesQueryParamFilter {
	if g == nil {
		return nil
	}
	return g.Filter
}

type GetMeshZoneAddressListAllMeshesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List
	MeshZoneAddressList *shared.MeshZoneAddressList
}

func (g *GetMeshZoneAddressListAllMeshesResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetMeshZoneAddressListAllMeshesResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetMeshZoneAddressListAllMeshesResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetMeshZoneAddressListAllMeshesResponse) GetMeshZoneAddressList() *shared.MeshZoneAddressList {
	if g == nil {
		return nil
	}
	return g.MeshZoneAddressList
}
