// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
	"net/http"
)

type GetMeshInsightListRequest struct {
	// Size of the page.
	Size *int64 `queryParam:"style=form,explode=true,name=size"`
	// Offset of the page to list.
	Offset *string `queryParam:"style=form,explode=true,name=offset"`
}

func (g *GetMeshInsightListRequest) GetSize() *int64 {
	if g == nil {
		return nil
	}
	return g.Size
}

func (g *GetMeshInsightListRequest) GetOffset() *string {
	if g == nil {
		return nil
	}
	return g.Offset
}

type GetMeshInsightListResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// A response containing a list of mesh insights.
	GetMeshInsightListResponse *shared.GetMeshInsightListResponse
	// Bad Request
	BadRequestError *shared.BadRequestError
	// Internal
	InternalError *shared.InternalError
}

func (g *GetMeshInsightListResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetMeshInsightListResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetMeshInsightListResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetMeshInsightListResponse) GetGetMeshInsightListResponse() *shared.GetMeshInsightListResponse {
	if g == nil {
		return nil
	}
	return g.GetMeshInsightListResponse
}

func (g *GetMeshInsightListResponse) GetBadRequestError() *shared.BadRequestError {
	if g == nil {
		return nil
	}
	return g.BadRequestError
}

func (g *GetMeshInsightListResponse) GetInternalError() *shared.InternalError {
	if g == nil {
		return nil
	}
	return g.InternalError
}
