// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/internal/utils"
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
	"net/http"
)

// GetMeshProxyPatchListAllMeshesQueryParamFilter - filter by labels when multiple filters are present, they are ANDed
type GetMeshProxyPatchListAllMeshesQueryParamFilter struct {
	Key   *string `queryParam:"name=key"`
	Value *string `queryParam:"name=value"`
}

func (g *GetMeshProxyPatchListAllMeshesQueryParamFilter) GetKey() *string {
	if g == nil {
		return nil
	}
	return g.Key
}

func (g *GetMeshProxyPatchListAllMeshesQueryParamFilter) GetValue() *string {
	if g == nil {
		return nil
	}
	return g.Value
}

type GetMeshProxyPatchListAllMeshesRequest struct {
	// offset in the list of entities
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
	// the number of items per page
	Size *int64 `default:"100" queryParam:"style=form,explode=true,name=size"`
	// filter by labels when multiple filters are present, they are ANDed
	Filter *GetMeshProxyPatchListAllMeshesQueryParamFilter `queryParam:"style=form,explode=true,name=filter"`
}

func (g GetMeshProxyPatchListAllMeshesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMeshProxyPatchListAllMeshesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetMeshProxyPatchListAllMeshesRequest) GetOffset() *int64 {
	if g == nil {
		return nil
	}
	return g.Offset
}

func (g *GetMeshProxyPatchListAllMeshesRequest) GetSize() *int64 {
	if g == nil {
		return nil
	}
	return g.Size
}

func (g *GetMeshProxyPatchListAllMeshesRequest) GetFilter() *GetMeshProxyPatchListAllMeshesQueryParamFilter {
	if g == nil {
		return nil
	}
	return g.Filter
}

type GetMeshProxyPatchListAllMeshesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List
	MeshProxyPatchList *shared.MeshProxyPatchList
}

func (g *GetMeshProxyPatchListAllMeshesResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetMeshProxyPatchListAllMeshesResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetMeshProxyPatchListAllMeshesResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetMeshProxyPatchListAllMeshesResponse) GetMeshProxyPatchList() *shared.MeshProxyPatchList {
	if g == nil {
		return nil
	}
	return g.MeshProxyPatchList
}
