// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/internal/utils"
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
	"net/http"
)

// GetMeshTCPRouteListAllMeshesQueryParamFilter - filter by labels when multiple filters are present, they are ANDed
type GetMeshTCPRouteListAllMeshesQueryParamFilter struct {
	Key   *string `queryParam:"name=key"`
	Value *string `queryParam:"name=value"`
}

func (g *GetMeshTCPRouteListAllMeshesQueryParamFilter) GetKey() *string {
	if g == nil {
		return nil
	}
	return g.Key
}

func (g *GetMeshTCPRouteListAllMeshesQueryParamFilter) GetValue() *string {
	if g == nil {
		return nil
	}
	return g.Value
}

type GetMeshTCPRouteListAllMeshesRequest struct {
	// offset in the list of entities
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
	// the number of items per page
	Size *int64 `default:"100" queryParam:"style=form,explode=true,name=size"`
	// filter by labels when multiple filters are present, they are ANDed
	Filter *GetMeshTCPRouteListAllMeshesQueryParamFilter `queryParam:"style=form,explode=true,name=filter"`
}

func (g GetMeshTCPRouteListAllMeshesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMeshTCPRouteListAllMeshesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetMeshTCPRouteListAllMeshesRequest) GetOffset() *int64 {
	if g == nil {
		return nil
	}
	return g.Offset
}

func (g *GetMeshTCPRouteListAllMeshesRequest) GetSize() *int64 {
	if g == nil {
		return nil
	}
	return g.Size
}

func (g *GetMeshTCPRouteListAllMeshesRequest) GetFilter() *GetMeshTCPRouteListAllMeshesQueryParamFilter {
	if g == nil {
		return nil
	}
	return g.Filter
}

type GetMeshTCPRouteListAllMeshesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List
	MeshTCPRouteList *shared.MeshTCPRouteList
}

func (g *GetMeshTCPRouteListAllMeshesResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetMeshTCPRouteListAllMeshesResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetMeshTCPRouteListAllMeshesResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetMeshTCPRouteListAllMeshesResponse) GetMeshTCPRouteList() *shared.MeshTCPRouteList {
	if g == nil {
		return nil
	}
	return g.MeshTCPRouteList
}
