// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
	"net/http"
)

type GetZoneInsightRequest struct {
	// name of the ZoneInsight
	Name string `pathParam:"style=simple,explode=false,name=name"`
}

func (g *GetZoneInsightRequest) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

type GetZoneInsightResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	ZoneInsightItem *shared.ZoneInsightItem
	// Not Found
	NotFoundError *shared.NotFoundError
}

func (g *GetZoneInsightResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetZoneInsightResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetZoneInsightResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetZoneInsightResponse) GetZoneInsightItem() *shared.ZoneInsightItem {
	if g == nil {
		return nil
	}
	return g.ZoneInsightItem
}

func (g *GetZoneInsightResponse) GetNotFoundError() *shared.NotFoundError {
	if g == nil {
		return nil
	}
	return g.NotFoundError
}
