// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
	"net/http"
)

type PostMeshTraceRequest struct {
	// name of the mesh
	Mesh string `pathParam:"style=simple,explode=false,name=mesh"`
	// Resource to create
	MeshTraceItem shared.MeshTraceItemInput `request:"mediaType=application/json"`
}

func (p *PostMeshTraceRequest) GetMesh() string {
	if p == nil {
		return ""
	}
	return p.Mesh
}

func (p *PostMeshTraceRequest) GetMeshTraceItem() shared.MeshTraceItemInput {
	if p == nil {
		return shared.MeshTraceItemInput{}
	}
	return p.MeshTraceItem
}

type PostMeshTraceResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	MeshTraceCreateOrUpdateSuccessResponse *shared.MeshTraceCreateOrUpdateSuccessResponse
	// Invalid resource
	Error *shared.Error
	// Parent mesh not found
	NotFoundError *shared.NotFoundError
}

func (p *PostMeshTraceResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PostMeshTraceResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PostMeshTraceResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PostMeshTraceResponse) GetMeshTraceCreateOrUpdateSuccessResponse() *shared.MeshTraceCreateOrUpdateSuccessResponse {
	if p == nil {
		return nil
	}
	return p.MeshTraceCreateOrUpdateSuccessResponse
}

func (p *PostMeshTraceResponse) GetError() *shared.Error {
	if p == nil {
		return nil
	}
	return p.Error
}

func (p *PostMeshTraceResponse) GetNotFoundError() *shared.NotFoundError {
	if p == nil {
		return nil
	}
	return p.NotFoundError
}
