// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
	"net/http"
)

type PostHostnameGeneratorResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	HostnameGeneratorCreateOrUpdateSuccessResponse *shared.HostnameGeneratorCreateOrUpdateSuccessResponse
	// Invalid resource
	Error *shared.Error
}

func (p *PostHostnameGeneratorResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PostHostnameGeneratorResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PostHostnameGeneratorResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PostHostnameGeneratorResponse) GetHostnameGeneratorCreateOrUpdateSuccessResponse() *shared.HostnameGeneratorCreateOrUpdateSuccessResponse {
	if p == nil {
		return nil
	}
	return p.HostnameGeneratorCreateOrUpdateSuccessResponse
}

func (p *PostHostnameGeneratorResponse) GetError() *shared.Error {
	if p == nil {
		return nil
	}
	return p.Error
}
