// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
	"net/http"
)

type PostMeshTCPRouteRequest struct {
	// name of the mesh
	Mesh string `pathParam:"style=simple,explode=false,name=mesh"`
	// Resource to create
	MeshTCPRouteItem shared.MeshTCPRouteItemInput `request:"mediaType=application/json"`
}

func (p *PostMeshTCPRouteRequest) GetMesh() string {
	if p == nil {
		return ""
	}
	return p.Mesh
}

func (p *PostMeshTCPRouteRequest) GetMeshTCPRouteItem() shared.MeshTCPRouteItemInput {
	if p == nil {
		return shared.MeshTCPRouteItemInput{}
	}
	return p.MeshTCPRouteItem
}

type PostMeshTCPRouteResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	MeshTCPRouteCreateOrUpdateSuccessResponse *shared.MeshTCPRouteCreateOrUpdateSuccessResponse
	// Invalid resource
	Error *shared.Error
	// Parent mesh not found
	NotFoundError *shared.NotFoundError
}

func (p *PostMeshTCPRouteResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PostMeshTCPRouteResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PostMeshTCPRouteResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PostMeshTCPRouteResponse) GetMeshTCPRouteCreateOrUpdateSuccessResponse() *shared.MeshTCPRouteCreateOrUpdateSuccessResponse {
	if p == nil {
		return nil
	}
	return p.MeshTCPRouteCreateOrUpdateSuccessResponse
}

func (p *PostMeshTCPRouteResponse) GetError() *shared.Error {
	if p == nil {
		return nil
	}
	return p.Error
}

func (p *PostMeshTCPRouteResponse) GetNotFoundError() *shared.NotFoundError {
	if p == nil {
		return nil
	}
	return p.NotFoundError
}
