// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
	"net/http"
)

type PostMeshZoneAddressRequest struct {
	// name of the mesh
	Mesh string `pathParam:"style=simple,explode=false,name=mesh"`
	// Resource to create
	MeshZoneAddressItem shared.MeshZoneAddressItemInput `request:"mediaType=application/json"`
}

func (p *PostMeshZoneAddressRequest) GetMesh() string {
	if p == nil {
		return ""
	}
	return p.Mesh
}

func (p *PostMeshZoneAddressRequest) GetMeshZoneAddressItem() shared.MeshZoneAddressItemInput {
	if p == nil {
		return shared.MeshZoneAddressItemInput{}
	}
	return p.MeshZoneAddressItem
}

type PostMeshZoneAddressResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	MeshZoneAddressCreateOrUpdateSuccessResponse *shared.MeshZoneAddressCreateOrUpdateSuccessResponse
	// Invalid resource
	Error *shared.Error
	// Parent mesh not found
	NotFoundError *shared.NotFoundError
}

func (p *PostMeshZoneAddressResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PostMeshZoneAddressResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PostMeshZoneAddressResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PostMeshZoneAddressResponse) GetMeshZoneAddressCreateOrUpdateSuccessResponse() *shared.MeshZoneAddressCreateOrUpdateSuccessResponse {
	if p == nil {
		return nil
	}
	return p.MeshZoneAddressCreateOrUpdateSuccessResponse
}

func (p *PostMeshZoneAddressResponse) GetError() *shared.Error {
	if p == nil {
		return nil
	}
	return p.Error
}

func (p *PostMeshZoneAddressResponse) GetNotFoundError() *shared.NotFoundError {
	if p == nil {
		return nil
	}
	return p.NotFoundError
}
