// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
	"net/http"
)

type PostZoneResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	ZoneCreateOrUpdateSuccessResponse *shared.ZoneCreateOrUpdateSuccessResponse
	// Invalid resource
	Error *shared.Error
}

func (p *PostZoneResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PostZoneResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PostZoneResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PostZoneResponse) GetZoneCreateOrUpdateSuccessResponse() *shared.ZoneCreateOrUpdateSuccessResponse {
	if p == nil {
		return nil
	}
	return p.ZoneCreateOrUpdateSuccessResponse
}

func (p *PostZoneResponse) GetError() *shared.Error {
	if p == nil {
		return nil
	}
	return p.Error
}
