// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
	"net/http"
)

type PostMeshTrafficPermissionRequest struct {
	// name of the mesh
	Mesh string `pathParam:"style=simple,explode=false,name=mesh"`
	// Resource to create
	MeshTrafficPermissionItem shared.MeshTrafficPermissionItemInput `request:"mediaType=application/json"`
}

func (p *PostMeshTrafficPermissionRequest) GetMesh() string {
	if p == nil {
		return ""
	}
	return p.Mesh
}

func (p *PostMeshTrafficPermissionRequest) GetMeshTrafficPermissionItem() shared.MeshTrafficPermissionItemInput {
	if p == nil {
		return shared.MeshTrafficPermissionItemInput{}
	}
	return p.MeshTrafficPermissionItem
}

type PostMeshTrafficPermissionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	MeshTrafficPermissionCreateOrUpdateSuccessResponse *shared.MeshTrafficPermissionCreateOrUpdateSuccessResponse
	// Invalid resource
	Error *shared.Error
	// Parent mesh not found
	NotFoundError *shared.NotFoundError
}

func (p *PostMeshTrafficPermissionResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PostMeshTrafficPermissionResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PostMeshTrafficPermissionResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PostMeshTrafficPermissionResponse) GetMeshTrafficPermissionCreateOrUpdateSuccessResponse() *shared.MeshTrafficPermissionCreateOrUpdateSuccessResponse {
	if p == nil {
		return nil
	}
	return p.MeshTrafficPermissionCreateOrUpdateSuccessResponse
}

func (p *PostMeshTrafficPermissionResponse) GetError() *shared.Error {
	if p == nil {
		return nil
	}
	return p.Error
}

func (p *PostMeshTrafficPermissionResponse) GetNotFoundError() *shared.NotFoundError {
	if p == nil {
		return nil
	}
	return p.NotFoundError
}
