// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
	"net/http"
)

type PostMeshAccessLogRequest struct {
	// name of the mesh
	Mesh string `pathParam:"style=simple,explode=false,name=mesh"`
	// Resource to create
	MeshAccessLogItem shared.MeshAccessLogItemInput `request:"mediaType=application/json"`
}

func (p *PostMeshAccessLogRequest) GetMesh() string {
	if p == nil {
		return ""
	}
	return p.Mesh
}

func (p *PostMeshAccessLogRequest) GetMeshAccessLogItem() shared.MeshAccessLogItemInput {
	if p == nil {
		return shared.MeshAccessLogItemInput{}
	}
	return p.MeshAccessLogItem
}

type PostMeshAccessLogResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	MeshAccessLogCreateOrUpdateSuccessResponse *shared.MeshAccessLogCreateOrUpdateSuccessResponse
	// Invalid resource
	Error *shared.Error
	// Parent mesh not found
	NotFoundError *shared.NotFoundError
}

func (p *PostMeshAccessLogResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PostMeshAccessLogResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PostMeshAccessLogResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PostMeshAccessLogResponse) GetMeshAccessLogCreateOrUpdateSuccessResponse() *shared.MeshAccessLogCreateOrUpdateSuccessResponse {
	if p == nil {
		return nil
	}
	return p.MeshAccessLogCreateOrUpdateSuccessResponse
}

func (p *PostMeshAccessLogResponse) GetError() *shared.Error {
	if p == nil {
		return nil
	}
	return p.Error
}

func (p *PostMeshAccessLogResponse) GetNotFoundError() *shared.NotFoundError {
	if p == nil {
		return nil
	}
	return p.NotFoundError
}
