// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
	"net/http"
)

type PostAccessRoleBindingResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	AccessRoleBindingCreateOrUpdateSuccessResponse *shared.AccessRoleBindingCreateOrUpdateSuccessResponse
	// Invalid resource
	Error *shared.Error
}

func (p *PostAccessRoleBindingResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PostAccessRoleBindingResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PostAccessRoleBindingResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PostAccessRoleBindingResponse) GetAccessRoleBindingCreateOrUpdateSuccessResponse() *shared.AccessRoleBindingCreateOrUpdateSuccessResponse {
	if p == nil {
		return nil
	}
	return p.AccessRoleBindingCreateOrUpdateSuccessResponse
}

func (p *PostAccessRoleBindingResponse) GetError() *shared.Error {
	if p == nil {
		return nil
	}
	return p.Error
}
