// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
	"net/http"
)

type PostMeshTrustRequest struct {
	// name of the mesh
	Mesh string `pathParam:"style=simple,explode=false,name=mesh"`
	// Resource to create
	MeshTrustItem shared.MeshTrustItemInput `request:"mediaType=application/json"`
}

func (p *PostMeshTrustRequest) GetMesh() string {
	if p == nil {
		return ""
	}
	return p.Mesh
}

func (p *PostMeshTrustRequest) GetMeshTrustItem() shared.MeshTrustItemInput {
	if p == nil {
		return shared.MeshTrustItemInput{}
	}
	return p.MeshTrustItem
}

type PostMeshTrustResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	MeshTrustCreateOrUpdateSuccessResponse *shared.MeshTrustCreateOrUpdateSuccessResponse
	// Invalid resource
	Error *shared.Error
	// Parent mesh not found
	NotFoundError *shared.NotFoundError
}

func (p *PostMeshTrustResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PostMeshTrustResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PostMeshTrustResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PostMeshTrustResponse) GetMeshTrustCreateOrUpdateSuccessResponse() *shared.MeshTrustCreateOrUpdateSuccessResponse {
	if p == nil {
		return nil
	}
	return p.MeshTrustCreateOrUpdateSuccessResponse
}

func (p *PostMeshTrustResponse) GetError() *shared.Error {
	if p == nil {
		return nil
	}
	return p.Error
}

func (p *PostMeshTrustResponse) GetNotFoundError() *shared.NotFoundError {
	if p == nil {
		return nil
	}
	return p.NotFoundError
}
