// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
	"net/http"
)

type PostMeshTimeoutRequest struct {
	// name of the mesh
	Mesh string `pathParam:"style=simple,explode=false,name=mesh"`
	// Resource to create
	MeshTimeoutItem shared.MeshTimeoutItemInput `request:"mediaType=application/json"`
}

func (p *PostMeshTimeoutRequest) GetMesh() string {
	if p == nil {
		return ""
	}
	return p.Mesh
}

func (p *PostMeshTimeoutRequest) GetMeshTimeoutItem() shared.MeshTimeoutItemInput {
	if p == nil {
		return shared.MeshTimeoutItemInput{}
	}
	return p.MeshTimeoutItem
}

type PostMeshTimeoutResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	MeshTimeoutCreateOrUpdateSuccessResponse *shared.MeshTimeoutCreateOrUpdateSuccessResponse
	// Invalid resource
	Error *shared.Error
	// Parent mesh not found
	NotFoundError *shared.NotFoundError
}

func (p *PostMeshTimeoutResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PostMeshTimeoutResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PostMeshTimeoutResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PostMeshTimeoutResponse) GetMeshTimeoutCreateOrUpdateSuccessResponse() *shared.MeshTimeoutCreateOrUpdateSuccessResponse {
	if p == nil {
		return nil
	}
	return p.MeshTimeoutCreateOrUpdateSuccessResponse
}

func (p *PostMeshTimeoutResponse) GetError() *shared.Error {
	if p == nil {
		return nil
	}
	return p.Error
}

func (p *PostMeshTimeoutResponse) GetNotFoundError() *shared.NotFoundError {
	if p == nil {
		return nil
	}
	return p.NotFoundError
}
