// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
	"net/http"
)

type PostMeshIdentityRequest struct {
	// name of the mesh
	Mesh string `pathParam:"style=simple,explode=false,name=mesh"`
	// Resource to create
	MeshIdentityItem shared.MeshIdentityItemInput `request:"mediaType=application/json"`
}

func (p *PostMeshIdentityRequest) GetMesh() string {
	if p == nil {
		return ""
	}
	return p.Mesh
}

func (p *PostMeshIdentityRequest) GetMeshIdentityItem() shared.MeshIdentityItemInput {
	if p == nil {
		return shared.MeshIdentityItemInput{}
	}
	return p.MeshIdentityItem
}

type PostMeshIdentityResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	MeshIdentityCreateOrUpdateSuccessResponse *shared.MeshIdentityCreateOrUpdateSuccessResponse
	// Invalid resource
	Error *shared.Error
	// Parent mesh not found
	NotFoundError *shared.NotFoundError
}

func (p *PostMeshIdentityResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PostMeshIdentityResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PostMeshIdentityResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PostMeshIdentityResponse) GetMeshIdentityCreateOrUpdateSuccessResponse() *shared.MeshIdentityCreateOrUpdateSuccessResponse {
	if p == nil {
		return nil
	}
	return p.MeshIdentityCreateOrUpdateSuccessResponse
}

func (p *PostMeshIdentityResponse) GetError() *shared.Error {
	if p == nil {
		return nil
	}
	return p.Error
}

func (p *PostMeshIdentityResponse) GetNotFoundError() *shared.NotFoundError {
	if p == nil {
		return nil
	}
	return p.NotFoundError
}
