// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
	"net/http"
)

type PostMeshTLSRequest struct {
	// name of the mesh
	Mesh string `pathParam:"style=simple,explode=false,name=mesh"`
	// Resource to create
	MeshTLSItem shared.MeshTLSItemInput `request:"mediaType=application/json"`
}

func (p *PostMeshTLSRequest) GetMesh() string {
	if p == nil {
		return ""
	}
	return p.Mesh
}

func (p *PostMeshTLSRequest) GetMeshTLSItem() shared.MeshTLSItemInput {
	if p == nil {
		return shared.MeshTLSItemInput{}
	}
	return p.MeshTLSItem
}

type PostMeshTLSResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	MeshTLSCreateOrUpdateSuccessResponse *shared.MeshTLSCreateOrUpdateSuccessResponse
	// Invalid resource
	Error *shared.Error
	// Parent mesh not found
	NotFoundError *shared.NotFoundError
}

func (p *PostMeshTLSResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PostMeshTLSResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PostMeshTLSResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PostMeshTLSResponse) GetMeshTLSCreateOrUpdateSuccessResponse() *shared.MeshTLSCreateOrUpdateSuccessResponse {
	if p == nil {
		return nil
	}
	return p.MeshTLSCreateOrUpdateSuccessResponse
}

func (p *PostMeshTLSResponse) GetError() *shared.Error {
	if p == nil {
		return nil
	}
	return p.Error
}

func (p *PostMeshTLSResponse) GetNotFoundError() *shared.NotFoundError {
	if p == nil {
		return nil
	}
	return p.NotFoundError
}
