// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
	"net/http"
)

type PutGlobalSecretAliasRequest struct {
	// name of the GlobalSecret
	Name string `pathParam:"style=simple,explode=false,name=name"`
	// Put request
	GlobalSecretItem shared.GlobalSecretItemInput `request:"mediaType=application/json"`
}

func (p *PutGlobalSecretAliasRequest) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PutGlobalSecretAliasRequest) GetGlobalSecretItem() shared.GlobalSecretItemInput {
	if p == nil {
		return shared.GlobalSecretItemInput{}
	}
	return p.GlobalSecretItem
}

type PutGlobalSecretAliasResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	GlobalSecretCreateOrUpdateSuccessResponse *shared.GlobalSecretCreateOrUpdateSuccessResponse
}

func (p *PutGlobalSecretAliasResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PutGlobalSecretAliasResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PutGlobalSecretAliasResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PutGlobalSecretAliasResponse) GetGlobalSecretCreateOrUpdateSuccessResponse() *shared.GlobalSecretCreateOrUpdateSuccessResponse {
	if p == nil {
		return nil
	}
	return p.GlobalSecretCreateOrUpdateSuccessResponse
}
