// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/internal/utils"
	"time"
)

type Access string

const (
	AccessCreate                   Access = "CREATE"
	AccessUpdate                   Access = "UPDATE"
	AccessDelete                   Access = "DELETE"
	AccessGenerateDataplaneToken   Access = "GENERATE_DATAPLANE_TOKEN"
	AccessGenerateUserToken        Access = "GENERATE_USER_TOKEN"
	AccessGenerateZoneCpToken      Access = "GENERATE_ZONE_CP_TOKEN"
	AccessGenerateZoneToken        Access = "GENERATE_ZONE_TOKEN"
	AccessViewConfigDump           Access = "VIEW_CONFIG_DUMP"
	AccessViewStats                Access = "VIEW_STATS"
	AccessViewClusters             Access = "VIEW_CLUSTERS"
	AccessViewControlPlaneMetadata Access = "VIEW_CONTROL_PLANE_METADATA"
)

func (e Access) ToPointer() *Access {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Access) IsExact() bool {
	if e != nil {
		switch *e {
		case "CREATE", "UPDATE", "DELETE", "GENERATE_DATAPLANE_TOKEN", "GENERATE_USER_TOKEN", "GENERATE_ZONE_CP_TOKEN", "GENERATE_ZONE_TOKEN", "VIEW_CONFIG_DUMP", "VIEW_STATS", "VIEW_CLUSTERS", "VIEW_CONTROL_PLANE_METADATA":
			return true
		}
	}
	return false
}

type Rules struct {
	Access    []Access `json:"access"`
	AccessAll *bool    `json:"accessAll,omitempty"`
	Mesh      *string  `json:"mesh,omitempty"`
	Types     []string `json:"types"`
}

func (r *Rules) GetAccess() []Access {
	if r == nil {
		return nil
	}
	return r.Access
}

func (r *Rules) GetAccessAll() *bool {
	if r == nil {
		return nil
	}
	return r.AccessAll
}

func (r *Rules) GetMesh() *string {
	if r == nil {
		return nil
	}
	return r.Mesh
}

func (r *Rules) GetTypes() []string {
	if r == nil {
		return nil
	}
	return r.Types
}

type AccessAuditItem struct {
	// Time at which the resource was created
	CreationTime *time.Time `json:"creationTime,omitempty"`
	// Kuma Resource Identifier (KRI) of the given resource
	Kri    *string           `json:"kri,omitempty"`
	Labels map[string]string `json:"labels,omitempty"`
	// Time at which the resource was updated
	ModificationTime *time.Time `json:"modificationTime,omitempty"`
	Name             string     `json:"name"`
	Rules            []Rules    `json:"rules"`
	Type             string     `json:"type"`
}

func (a AccessAuditItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccessAuditItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AccessAuditItem) GetCreationTime() *time.Time {
	if a == nil {
		return nil
	}
	return a.CreationTime
}

func (a *AccessAuditItem) GetKri() *string {
	if a == nil {
		return nil
	}
	return a.Kri
}

func (a *AccessAuditItem) GetLabels() map[string]string {
	if a == nil {
		return nil
	}
	return a.Labels
}

func (a *AccessAuditItem) GetModificationTime() *time.Time {
	if a == nil {
		return nil
	}
	return a.ModificationTime
}

func (a *AccessAuditItem) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AccessAuditItem) GetRules() []Rules {
	if a == nil {
		return nil
	}
	return a.Rules
}

func (a *AccessAuditItem) GetType() string {
	if a == nil {
		return ""
	}
	return a.Type
}

type AccessAuditItemInput struct {
	Labels map[string]string `json:"labels,omitempty"`
	Name   string            `json:"name"`
	Rules  []Rules           `json:"rules"`
	Type   string            `json:"type"`
}

func (a *AccessAuditItemInput) GetLabels() map[string]string {
	if a == nil {
		return nil
	}
	return a.Labels
}

func (a *AccessAuditItemInput) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AccessAuditItemInput) GetRules() []Rules {
	if a == nil {
		return nil
	}
	return a.Rules
}

func (a *AccessAuditItemInput) GetType() string {
	if a == nil {
		return ""
	}
	return a.Type
}
