// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// AccessRoleList - List
type AccessRoleList struct {
	Items []AccessRoleItem `json:"items"`
	// URL to the next page, or null when this is the last page
	Next *string `json:"next"`
	// The total number of entities
	Total float64 `json:"total"`
}

func (a *AccessRoleList) GetItems() []AccessRoleItem {
	if a == nil {
		return []AccessRoleItem{}
	}
	return a.Items
}

func (a *AccessRoleList) GetNext() *string {
	if a == nil {
		return nil
	}
	return a.Next
}

func (a *AccessRoleList) GetTotal() float64 {
	if a == nil {
		return 0.0
	}
	return a.Total
}
