// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DataSourceFile struct {
	Type *string `json:"type,omitempty"`
	// Data source is a path to a file.
	// Deprecated, use other sources of a data.
	File *string `json:"File,omitempty"`
}

func (o *DataSourceFile) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *DataSourceFile) GetFile() *string {
	if o == nil {
		return nil
	}
	return o.File
}
