// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DataSourceSecret struct {
	Type *string `json:"type,omitempty"`
	// Data source is a secret with given Secret key.
	Secret *string `json:"Secret,omitempty"`
}

func (o *DataSourceSecret) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *DataSourceSecret) GetSecret() *string {
	if o == nil {
		return nil
	}
	return o.Secret
}
