// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// DataplaneInsightList - List
type DataplaneInsightList struct {
	Items []DataplaneInsightItem `json:"items"`
	// URL to the next page, or null when this is the last page
	Next *string `json:"next"`
	// The total number of entities
	Total float64 `json:"total"`
}

func (d *DataplaneInsightList) GetItems() []DataplaneInsightItem {
	if d == nil {
		return []DataplaneInsightItem{}
	}
	return d.Items
}

func (d *DataplaneInsightList) GetNext() *string {
	if d == nil {
		return nil
	}
	return d.Next
}

func (d *DataplaneInsightList) GetTotal() float64 {
	if d == nil {
		return 0.0
	}
	return d.Total
}
