// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// Error - Standard error. Follows the [AIP #193 - Errors](https://kong-aip.netlify.app/aip/193/) specification.
type Error struct {
	// The HTTP status code.
	Status int64 `json:"status"`
	// A short, human-readable summary of the problem.
	// It **should not** change between occurrences of a problem, except for localization.
	// Should be provided as "Sentence case" for potential direct use in a UI
	//
	Title string `json:"title"`
	// A unique identifier for this error. When dereferenced it must provide human-readable documentation for the problem.
	//
	Type string `json:"type"`
	// Used to return the correlation ID back to the user, in the format `<app>:trace:<correlation_id>`.
	//
	Instance string `json:"instance"`
	// A human readable explanation specific to this occurrence of the problem.
	// This field may contain request/entity data to help the user understand what went wrong.
	// Enclose variable values in square brackets.
	// _Should_ be provided as "Sentence case" for direct use in a UI
	//
	Detail string `json:"detail"`
	// All 400 errors **MUST** return an `invalid_parameters` key in the response.
	// Used to indicate which fields have invalid values when validated.
	//
	InvalidParameters [][]InvalidParameters `json:"invalid_parameters,omitempty"`
}

func (e *Error) GetStatus() int64 {
	if e == nil {
		return 0
	}
	return e.Status
}

func (e *Error) GetTitle() string {
	if e == nil {
		return ""
	}
	return e.Title
}

func (e *Error) GetType() string {
	if e == nil {
		return ""
	}
	return e.Type
}

func (e *Error) GetInstance() string {
	if e == nil {
		return ""
	}
	return e.Instance
}

func (e *Error) GetDetail() string {
	if e == nil {
		return ""
	}
	return e.Detail
}

func (e *Error) GetInvalidParameters() [][]InvalidParameters {
	if e == nil {
		return nil
	}
	return e.InvalidParameters
}
