// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// GetMeshInsightListResponse - A response containing a list of mesh insights.
type GetMeshInsightListResponse struct {
	Total int64 `json:"total"`
	// URL to the next page, or null when this is the last page
	Next  *string               `json:"next"`
	Items []MeshInsightWithMeta `json:"items"`
}

func (g *GetMeshInsightListResponse) GetTotal() int64 {
	if g == nil {
		return 0
	}
	return g.Total
}

func (g *GetMeshInsightListResponse) GetNext() *string {
	if g == nil {
		return nil
	}
	return g.Next
}

func (g *GetMeshInsightListResponse) GetItems() []MeshInsightWithMeta {
	if g == nil {
		return []MeshInsightWithMeta{}
	}
	return g.Items
}
