// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/internal/utils"
	"time"
)

// HostnameGeneratorItemType - the type of the resource
type HostnameGeneratorItemType string

const (
	HostnameGeneratorItemTypeHostnameGenerator HostnameGeneratorItemType = "HostnameGenerator"
)

func (e HostnameGeneratorItemType) ToPointer() *HostnameGeneratorItemType {
	return &e
}
func (e *HostnameGeneratorItemType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "HostnameGenerator":
		*e = HostnameGeneratorItemType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for HostnameGeneratorItemType: %v", v)
	}
}

// Other - An extension this control plane does not ship. Its configuration is not described here.
type Other struct {
	// Type of the extension.
	Type string `json:"type"`
	// Config freeform configuration for the extension.
	Config any `default:"null" json:"config"`
}

func (o Other) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *Other) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *Other) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *Other) GetConfig() any {
	if o == nil {
		return nil
	}
	return o.Config
}

type Route53 struct {
	// Config freeform configuration for the extension.
	Config any `default:"null" json:"config"`
	// Type of the extension.
	Type string `json:"type"`
}

func (r Route53) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *Route53) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *Route53) GetConfig() any {
	if r == nil {
		return nil
	}
	return r.Config
}

func (r *Route53) GetType() string {
	if r == nil {
		return ""
	}
	return r.Type
}

// #region class-body-route53
// #endregion class-body-route53

type ExtensionType string

const (
	ExtensionTypeRoute53 ExtensionType = "Route53"
	ExtensionTypeOther   ExtensionType = "Other"
)

// Extension struct for a plugin configuration
type Extension struct {
	Route53 *Route53 `queryParam:"inline" union:"member"`
	Other   *Other   `queryParam:"inline" union:"member"`

	Type ExtensionType
}

func CreateExtensionRoute53(route53 Route53) Extension {
	typ := ExtensionTypeRoute53

	return Extension{
		Route53: &route53,
		Type:    typ,
	}
}

func CreateExtensionOther(other Other) Extension {
	typ := ExtensionTypeOther

	return Extension{
		Other: &other,
		Type:  typ,
	}
}

func (u *Extension) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var route53 Route53 = Route53{}
	if err := utils.UnmarshalJSON(data, &route53, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ExtensionTypeRoute53,
			Value: &route53,
		})
	}

	var other Other = Other{}
	if err := utils.UnmarshalJSON(data, &other, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ExtensionTypeOther,
			Value: &other,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Extension", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Extension", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(ExtensionType)
	switch best.Type {
	case ExtensionTypeRoute53:
		u.Route53 = best.Value.(*Route53)
		return nil
	case ExtensionTypeOther:
		u.Other = best.Value.(*Other)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Extension", string(data))
}

func (u Extension) MarshalJSON() ([]byte, error) {
	if u.Route53 != nil {
		return utils.MarshalJSON(u.Route53, "", true)
	}

	if u.Other != nil {
		return utils.MarshalJSON(u.Other, "", true)
	}

	return nil, errors.New("could not marshal union type Extension: all fields are null")
}

type MeshExternalService struct {
	MatchLabels map[string]string `json:"matchLabels,omitempty"`
}

func (m *MeshExternalService) GetMatchLabels() map[string]string {
	if m == nil {
		return nil
	}
	return m.MatchLabels
}

type MeshMultiZoneService struct {
	MatchLabels map[string]string `json:"matchLabels,omitempty"`
}

func (m *MeshMultiZoneService) GetMatchLabels() map[string]string {
	if m == nil {
		return nil
	}
	return m.MatchLabels
}

type MeshService struct {
	MatchLabels map[string]string `json:"matchLabels,omitempty"`
}

func (m *MeshService) GetMatchLabels() map[string]string {
	if m == nil {
		return nil
	}
	return m.MatchLabels
}

type Selector struct {
	MeshExternalService  *MeshExternalService  `json:"meshExternalService,omitempty"`
	MeshMultiZoneService *MeshMultiZoneService `json:"meshMultiZoneService,omitempty"`
	MeshService          *MeshService          `json:"meshService,omitempty"`
}

func (s *Selector) GetMeshExternalService() *MeshExternalService {
	if s == nil {
		return nil
	}
	return s.MeshExternalService
}

func (s *Selector) GetMeshMultiZoneService() *MeshMultiZoneService {
	if s == nil {
		return nil
	}
	return s.MeshMultiZoneService
}

func (s *Selector) GetMeshService() *MeshService {
	if s == nil {
		return nil
	}
	return s.MeshService
}

// HostnameGeneratorItemSpec - Spec is the specification of the Kuma HostnameGenerator resource.
type HostnameGeneratorItemSpec struct {
	// Extension struct for a plugin configuration
	Extension *Extension `json:"extension,omitempty"`
	Selector  *Selector  `json:"selector,omitempty"`
	Template  string     `json:"template"`
}

func (h *HostnameGeneratorItemSpec) GetExtension() *Extension {
	if h == nil {
		return nil
	}
	return h.Extension
}

func (h *HostnameGeneratorItemSpec) GetSelector() *Selector {
	if h == nil {
		return nil
	}
	return h.Selector
}

func (h *HostnameGeneratorItemSpec) GetTemplate() string {
	if h == nil {
		return ""
	}
	return h.Template
}

// HostnameGeneratorItem - HostnameGenerator automatically generates DNS hostnames for services in the mesh based on customizable templates. It provides a consistent naming scheme for service discovery by creating predictable hostnames from service labels and metadata, supporting both MeshService, MeshExternalService, and MeshMultiZoneService resources.
type HostnameGeneratorItem struct {
	// the type of the resource
	Type HostnameGeneratorItemType `json:"type"`
	// A unique identifier for this resource instance used by internal tooling and integrations. Typically derived from resource attributes and may be used for cross-references or indexing
	Kri *string `json:"kri,omitempty"`
	// Name of the Kuma resource
	Name string `json:"name"`
	// The labels to help identity resources
	Labels map[string]string `json:"labels,omitempty"`
	// Spec is the specification of the Kuma HostnameGenerator resource.
	Spec HostnameGeneratorItemSpec `json:"spec"`
	// Time at which the resource was created
	CreationTime *time.Time `json:"creationTime,omitempty"`
	// Time at which the resource was updated
	ModificationTime *time.Time `json:"modificationTime,omitempty"`
}

func (h HostnameGeneratorItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(h, "", false)
}

func (h *HostnameGeneratorItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &h, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (h *HostnameGeneratorItem) GetType() HostnameGeneratorItemType {
	if h == nil {
		return HostnameGeneratorItemType("")
	}
	return h.Type
}

func (h *HostnameGeneratorItem) GetKri() *string {
	if h == nil {
		return nil
	}
	return h.Kri
}

func (h *HostnameGeneratorItem) GetName() string {
	if h == nil {
		return ""
	}
	return h.Name
}

func (h *HostnameGeneratorItem) GetLabels() map[string]string {
	if h == nil {
		return nil
	}
	return h.Labels
}

func (h *HostnameGeneratorItem) GetSpec() HostnameGeneratorItemSpec {
	if h == nil {
		return HostnameGeneratorItemSpec{}
	}
	return h.Spec
}

func (h *HostnameGeneratorItem) GetCreationTime() *time.Time {
	if h == nil {
		return nil
	}
	return h.CreationTime
}

func (h *HostnameGeneratorItem) GetModificationTime() *time.Time {
	if h == nil {
		return nil
	}
	return h.ModificationTime
}

// HostnameGeneratorItemInput - HostnameGenerator automatically generates DNS hostnames for services in the mesh based on customizable templates. It provides a consistent naming scheme for service discovery by creating predictable hostnames from service labels and metadata, supporting both MeshService, MeshExternalService, and MeshMultiZoneService resources.
type HostnameGeneratorItemInput struct {
	// the type of the resource
	Type HostnameGeneratorItemType `json:"type"`
	// Name of the Kuma resource
	Name string `json:"name"`
	// The labels to help identity resources
	Labels map[string]string `json:"labels,omitempty"`
	// Spec is the specification of the Kuma HostnameGenerator resource.
	Spec HostnameGeneratorItemSpec `json:"spec"`
}

func (h *HostnameGeneratorItemInput) GetType() HostnameGeneratorItemType {
	if h == nil {
		return HostnameGeneratorItemType("")
	}
	return h.Type
}

func (h *HostnameGeneratorItemInput) GetName() string {
	if h == nil {
		return ""
	}
	return h.Name
}

func (h *HostnameGeneratorItemInput) GetLabels() map[string]string {
	if h == nil {
		return nil
	}
	return h.Labels
}

func (h *HostnameGeneratorItemInput) GetSpec() HostnameGeneratorItemSpec {
	if h == nil {
		return HostnameGeneratorItemSpec{}
	}
	return h.Spec
}
