// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/internal/utils"
	"time"
)

// LicenseType - Type of the license
type LicenseType string

const (
	LicenseTypeDemo      LicenseType = "demo"
	LicenseTypeDataplane LicenseType = "dataplane"
	LicenseTypeZone      LicenseType = "zone"
)

func (e LicenseType) ToPointer() *LicenseType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *LicenseType) IsExact() bool {
	if e != nil {
		switch *e {
		case "demo", "dataplane", "zone":
			return true
		}
	}
	return false
}

// License information of the control plane
type License struct {
	// Type of the license
	Type LicenseType `json:"type"`
	// Whether the control plane runs on a demo license
	Demo bool `json:"demo"`
	// Maximum number of dataplane proxies allowed by the license. Non-zero only for demo and dataplane licenses.
	AllowedDataplaneProxies int64 `json:"allowedDataplaneProxies"`
	// Current number of active dataplane proxies. Non-zero only for demo and dataplane licenses.
	ActiveDataplaneProxies int64 `json:"activeDataplaneProxies"`
	// Maximum number of zones allowed by the license. Non-zero only for zone licenses.
	AllowedZones int64 `json:"allowedZones"`
	// Current number of active zones. Non-zero only for zone licenses.
	ActiveZones int64 `json:"activeZones"`
	// Date the license expires
	ExpirationDate time.Time `json:"expirationDate"`
}

func (l License) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *License) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *License) GetType() LicenseType {
	if l == nil {
		return LicenseType("")
	}
	return l.Type
}

func (l *License) GetDemo() bool {
	if l == nil {
		return false
	}
	return l.Demo
}

func (l *License) GetAllowedDataplaneProxies() int64 {
	if l == nil {
		return 0
	}
	return l.AllowedDataplaneProxies
}

func (l *License) GetActiveDataplaneProxies() int64 {
	if l == nil {
		return 0
	}
	return l.ActiveDataplaneProxies
}

func (l *License) GetAllowedZones() int64 {
	if l == nil {
		return 0
	}
	return l.AllowedZones
}

func (l *License) GetActiveZones() int64 {
	if l == nil {
		return 0
	}
	return l.ActiveZones
}

func (l *License) GetExpirationDate() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.ExpirationDate
}
