// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// MeshZoneAddressList - List
type MeshZoneAddressList struct {
	Items []MeshZoneAddressItem `json:"items"`
	// The total number of entities
	Total float64 `json:"total"`
	// URL to the next page, or null when this is the last page
	Next *string `json:"next"`
}

func (m *MeshZoneAddressList) GetItems() []MeshZoneAddressItem {
	if m == nil {
		return []MeshZoneAddressItem{}
	}
	return m.Items
}

func (m *MeshZoneAddressList) GetTotal() float64 {
	if m == nil {
		return 0.0
	}
	return m.Total
}

func (m *MeshZoneAddressList) GetNext() *string {
	if m == nil {
		return nil
	}
	return m.Next
}
