// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// MeshTraceList - List
type MeshTraceList struct {
	Items []MeshTraceItem `json:"items"`
	// The total number of entities
	Total float64 `json:"total"`
	// URL to the next page, or null when this is the last page
	Next *string `json:"next"`
}

func (m *MeshTraceList) GetItems() []MeshTraceItem {
	if m == nil {
		return []MeshTraceItem{}
	}
	return m.Items
}

func (m *MeshTraceList) GetTotal() float64 {
	if m == nil {
		return 0.0
	}
	return m.Total
}

func (m *MeshTraceList) GetNext() *string {
	if m == nil {
		return nil
	}
	return m.Next
}
