// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// MeshTLSList - List
type MeshTLSList struct {
	Items []MeshTLSItem `json:"items"`
	// The total number of entities
	Total float64 `json:"total"`
	// URL to the next page, or null when this is the last page
	Next *string `json:"next"`
}

func (m *MeshTLSList) GetItems() []MeshTLSItem {
	if m == nil {
		return []MeshTLSItem{}
	}
	return m.Items
}

func (m *MeshTLSList) GetTotal() float64 {
	if m == nil {
		return 0.0
	}
	return m.Total
}

func (m *MeshTLSList) GetNext() *string {
	if m == nil {
		return nil
	}
	return m.Next
}
