// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// MeshMultiZoneServiceList - List
type MeshMultiZoneServiceList struct {
	Items []MeshMultiZoneServiceItem `json:"items"`
	// The total number of entities
	Total float64 `json:"total"`
	// URL to the next page, or null when this is the last page
	Next *string `json:"next"`
}

func (m *MeshMultiZoneServiceList) GetItems() []MeshMultiZoneServiceItem {
	if m == nil {
		return []MeshMultiZoneServiceItem{}
	}
	return m.Items
}

func (m *MeshMultiZoneServiceList) GetTotal() float64 {
	if m == nil {
		return 0.0
	}
	return m.Total
}

func (m *MeshMultiZoneServiceList) GetNext() *string {
	if m == nil {
		return nil
	}
	return m.Next
}
