// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// MeshTimeoutList - List
type MeshTimeoutList struct {
	Items []MeshTimeoutItem `json:"items"`
	// The total number of entities
	Total float64 `json:"total"`
	// URL to the next page, or null when this is the last page
	Next *string `json:"next"`
}

func (m *MeshTimeoutList) GetItems() []MeshTimeoutItem {
	if m == nil {
		return []MeshTimeoutItem{}
	}
	return m.Items
}

func (m *MeshTimeoutList) GetTotal() float64 {
	if m == nil {
		return 0.0
	}
	return m.Total
}

func (m *MeshTimeoutList) GetNext() *string {
	if m == nil {
		return nil
	}
	return m.Next
}
