// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/internal/utils"
	"time"
)

type Mode string

const (
	ModeDisabled          Mode = "Disabled"
	ModeEverywhere        Mode = "Everywhere"
	ModeReachableBackends Mode = "ReachableBackends"
	ModeExclusive         Mode = "Exclusive"
)

func (e Mode) ToPointer() *Mode {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Mode) IsExact() bool {
	if e != nil {
		switch *e {
		case "Disabled", "Everywhere", "ReachableBackends", "Exclusive":
			return true
		}
	}
	return false
}

// MeshServices - Deprecated: ignored since 3.0, where every mesh behaves as Exclusive.
// Kept only so pre-3.0 zones keep receiving the mode over KDS.
//
// Deprecated: Marked as deprecated in api/mesh/v1alpha1/mesh.proto.
type MeshServices struct {
	Mode *Mode `json:"mode,omitempty"`
}

func (m *MeshServices) GetMode() *Mode {
	if m == nil {
		return nil
	}
	return m.Mode
}

type MeshItem struct {
	// Time at which the resource was created
	CreationTime *time.Time `json:"creationTime,omitempty"`
	// Kuma Resource Identifier (KRI) of the given resource
	Kri    *string           `json:"kri,omitempty"`
	Labels map[string]string `json:"labels,omitempty"`
	// Deprecated: ignored since 3.0, where every mesh behaves as Exclusive.
	// Kept only so pre-3.0 zones keep receiving the mode over KDS.
	//
	// Deprecated: Marked as deprecated in api/mesh/v1alpha1/mesh.proto.
	MeshServices *MeshServices `json:"meshServices,omitempty"`
	// Time at which the resource was updated
	ModificationTime *time.Time `json:"modificationTime,omitempty"`
	Name             string     `json:"name"`
	Type             string     `json:"type"`
}

func (m MeshItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MeshItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MeshItem) GetCreationTime() *time.Time {
	if m == nil {
		return nil
	}
	return m.CreationTime
}

func (m *MeshItem) GetKri() *string {
	if m == nil {
		return nil
	}
	return m.Kri
}

func (m *MeshItem) GetLabels() map[string]string {
	if m == nil {
		return nil
	}
	return m.Labels
}

func (m *MeshItem) GetMeshServices() *MeshServices {
	if m == nil {
		return nil
	}
	return m.MeshServices
}

func (m *MeshItem) GetModificationTime() *time.Time {
	if m == nil {
		return nil
	}
	return m.ModificationTime
}

func (m *MeshItem) GetName() string {
	if m == nil {
		return ""
	}
	return m.Name
}

func (m *MeshItem) GetType() string {
	if m == nil {
		return ""
	}
	return m.Type
}

type MeshItemInput struct {
	Labels map[string]string `json:"labels,omitempty"`
	// Deprecated: ignored since 3.0, where every mesh behaves as Exclusive.
	// Kept only so pre-3.0 zones keep receiving the mode over KDS.
	//
	// Deprecated: Marked as deprecated in api/mesh/v1alpha1/mesh.proto.
	MeshServices *MeshServices `json:"meshServices,omitempty"`
	Name         string        `json:"name"`
	Type         string        `json:"type"`
}

func (m *MeshItemInput) GetLabels() map[string]string {
	if m == nil {
		return nil
	}
	return m.Labels
}

func (m *MeshItemInput) GetMeshServices() *MeshServices {
	if m == nil {
		return nil
	}
	return m.MeshServices
}

func (m *MeshItemInput) GetName() string {
	if m == nil {
		return ""
	}
	return m.Name
}

func (m *MeshItemInput) GetType() string {
	if m == nil {
		return ""
	}
	return m.Type
}
