// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// MeshLoadBalancingStrategyList - List
type MeshLoadBalancingStrategyList struct {
	Items []MeshLoadBalancingStrategyItem `json:"items"`
	// The total number of entities
	Total float64 `json:"total"`
	// URL to the next page, or null when this is the last page
	Next *string `json:"next"`
}

func (m *MeshLoadBalancingStrategyList) GetItems() []MeshLoadBalancingStrategyItem {
	if m == nil {
		return []MeshLoadBalancingStrategyItem{}
	}
	return m.Items
}

func (m *MeshLoadBalancingStrategyList) GetTotal() float64 {
	if m == nil {
		return 0.0
	}
	return m.Total
}

func (m *MeshLoadBalancingStrategyList) GetNext() *string {
	if m == nil {
		return nil
	}
	return m.Next
}
