// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// SecretList - List
type SecretList struct {
	Items []SecretItem `json:"items"`
	// URL to the next page, or null when this is the last page
	Next *string `json:"next"`
	// The total number of entities
	Total float64 `json:"total"`
}

func (s *SecretList) GetItems() []SecretItem {
	if s == nil {
		return []SecretItem{}
	}
	return s.Items
}

func (s *SecretList) GetNext() *string {
	if s == nil {
		return nil
	}
	return s.Next
}

func (s *SecretList) GetTotal() float64 {
	if s == nil {
		return 0.0
	}
	return s.Total
}
