// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// ZoneInsightList - List
type ZoneInsightList struct {
	Items []ZoneInsightItem `json:"items"`
	// URL to the next page, or null when this is the last page
	Next *string `json:"next"`
	// The total number of entities
	Total float64 `json:"total"`
}

func (z *ZoneInsightList) GetItems() []ZoneInsightItem {
	if z == nil {
		return []ZoneInsightItem{}
	}
	return z.Items
}

func (z *ZoneInsightList) GetNext() *string {
	if z == nil {
		return nil
	}
	return z.Next
}

func (z *ZoneInsightList) GetTotal() float64 {
	if z == nil {
		return 0.0
	}
	return z.Total
}
