// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/kong/terraform-provider-kong-mesh/internal/provider/typeconvert"
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/operations"
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
)

func (r *MeshZoneResourceModel) RefreshFromSharedZoneCreateOrUpdateSuccessResponse(ctx context.Context, resp *shared.ZoneCreateOrUpdateSuccessResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.Warnings = make([]types.String, 0, len(resp.Warnings))
		for _, v := range resp.Warnings {
			r.Warnings = append(r.Warnings, types.StringValue(v))
		}
	}

	return diags
}

func (r *MeshZoneResourceModel) RefreshFromSharedZoneItem(ctx context.Context, resp *shared.ZoneItem) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.CreationTime = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.CreationTime))
		r.Enabled = types.BoolPointerValue(resp.Enabled)
		r.Kri = types.StringPointerValue(resp.Kri)
		if len(resp.Labels) > 0 {
			r.Labels = make(map[string]types.String, len(resp.Labels))
			for key, value := range resp.Labels {
				r.Labels[key] = types.StringValue(value)
			}
		}
		r.ModificationTime = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.ModificationTime))
		r.Name = types.StringValue(resp.Name)
		r.Type = types.StringValue(resp.Type)
	}

	return diags
}

func (r *MeshZoneResourceModel) ToOperationsDeleteZoneRequest(ctx context.Context) (*operations.DeleteZoneRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var name string
	name = r.Name.ValueString()

	out := operations.DeleteZoneRequest{
		Name: name,
	}

	return &out, diags
}

func (r *MeshZoneResourceModel) ToOperationsGetZoneRequest(ctx context.Context) (*operations.GetZoneRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var name string
	name = r.Name.ValueString()

	out := operations.GetZoneRequest{
		Name: name,
	}

	return &out, diags
}

func (r *MeshZoneResourceModel) ToOperationsPutZoneRequest(ctx context.Context) (*operations.PutZoneRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var name string
	name = r.Name.ValueString()

	zoneItem, zoneItemDiags := r.ToSharedZoneItemInput(ctx)
	diags.Append(zoneItemDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.PutZoneRequest{
		Name:     name,
		ZoneItem: *zoneItem,
	}

	return &out, diags
}

func (r *MeshZoneResourceModel) ToSharedZoneItemInput(ctx context.Context) (*shared.ZoneItemInput, diag.Diagnostics) {
	var diags diag.Diagnostics

	enabled := new(bool)
	if !r.Enabled.IsUnknown() && !r.Enabled.IsNull() {
		*enabled = r.Enabled.ValueBool()
	} else {
		enabled = nil
	}
	labels := make(map[string]string)
	for labelsKey := range r.Labels {
		var labelsInst string
		labelsInst = r.Labels[labelsKey].ValueString()

		labels[labelsKey] = labelsInst
	}
	var name string
	name = r.Name.ValueString()

	var typeVar string
	typeVar = r.Type.ValueString()

	out := shared.ZoneItemInput{
		Enabled: enabled,
		Labels:  labels,
		Name:    name,
		Type:    typeVar,
	}

	return &out, diags
}
