// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	tfTypes "github.com/kong/terraform-provider-kong-mesh/internal/provider/types"
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/operations"
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
)

func (r *MeshAccessAuditResourceModel) RefreshFromSharedAccessAuditCreateOrUpdateSuccessResponse(ctx context.Context, resp *shared.AccessAuditCreateOrUpdateSuccessResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.Warnings = make([]types.String, 0, len(resp.Warnings))
		for _, v := range resp.Warnings {
			r.Warnings = append(r.Warnings, types.StringValue(v))
		}
	}

	return diags
}

func (r *MeshAccessAuditResourceModel) RefreshFromSharedAccessAuditItem(ctx context.Context, resp *shared.AccessAuditItem) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		if len(resp.Labels) > 0 {
			r.Labels = make(map[string]types.String, len(resp.Labels))
			for key, value := range resp.Labels {
				r.Labels[key] = types.StringValue(value)
			}
		}
		r.Name = types.StringValue(resp.Name)
		if resp.Rules != nil {
			r.Rules = []tfTypes.Rules{}

			for _, rulesItem := range resp.Rules {
				var rules tfTypes.Rules

				if rulesItem.Access != nil {
					rules.Access = []tfTypes.Mode{}

					for _, accessItem := range rulesItem.Access {
						var access tfTypes.Mode

						if accessItem.Str != nil {
							access.Str = types.StringPointerValue(accessItem.Str)
						}
						if accessItem.Integer != nil {
							access.Integer = types.Int64PointerValue(accessItem.Integer)
						}

						rules.Access = append(rules.Access, access)
					}
				}
				rules.AccessAll = types.BoolPointerValue(rulesItem.AccessAll)
				rules.Mesh = types.StringPointerValue(rulesItem.Mesh)
				if rulesItem.Types != nil {
					rules.Types = make([]types.String, 0, len(rulesItem.Types))
					for _, v := range rulesItem.Types {
						rules.Types = append(rules.Types, types.StringValue(v))
					}
				}

				r.Rules = append(r.Rules, rules)
			}
		}
		r.Type = types.StringValue(resp.Type)
	}

	return diags
}

func (r *MeshAccessAuditResourceModel) ToOperationsDeleteAccessAuditRequest(ctx context.Context) (*operations.DeleteAccessAuditRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var name string
	name = r.Name.ValueString()

	out := operations.DeleteAccessAuditRequest{
		Name: name,
	}

	return &out, diags
}

func (r *MeshAccessAuditResourceModel) ToOperationsGetAccessAuditRequest(ctx context.Context) (*operations.GetAccessAuditRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var name string
	name = r.Name.ValueString()

	out := operations.GetAccessAuditRequest{
		Name: name,
	}

	return &out, diags
}

func (r *MeshAccessAuditResourceModel) ToOperationsPutAccessAuditRequest(ctx context.Context) (*operations.PutAccessAuditRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var name string
	name = r.Name.ValueString()

	accessAuditItem, accessAuditItemDiags := r.ToSharedAccessAuditItem(ctx)
	diags.Append(accessAuditItemDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.PutAccessAuditRequest{
		Name:            name,
		AccessAuditItem: *accessAuditItem,
	}

	return &out, diags
}

func (r *MeshAccessAuditResourceModel) ToSharedAccessAuditItem(ctx context.Context) (*shared.AccessAuditItem, diag.Diagnostics) {
	var diags diag.Diagnostics

	labels := make(map[string]string)
	for labelsKey, labelsValue := range r.Labels {
		var labelsInst string
		labelsInst = labelsValue.ValueString()

		labels[labelsKey] = labelsInst
	}
	var name string
	name = r.Name.ValueString()

	var rules []shared.Rules
	if r.Rules != nil {
		rules = make([]shared.Rules, 0, len(r.Rules))
		for _, rulesItem := range r.Rules {
			var access []shared.Access
			if rulesItem.Access != nil {
				access = make([]shared.Access, 0, len(rulesItem.Access))
				for _, accessItem := range rulesItem.Access {
					if !accessItem.Str.IsUnknown() && !accessItem.Str.IsNull() {
						var str string
						str = accessItem.Str.ValueString()

						access = append(access, shared.Access{
							Str: &str,
						})
					}
					if !accessItem.Integer.IsUnknown() && !accessItem.Integer.IsNull() {
						var integer int64
						integer = accessItem.Integer.ValueInt64()

						access = append(access, shared.Access{
							Integer: &integer,
						})
					}
				}
			}
			accessAll := new(bool)
			if !rulesItem.AccessAll.IsUnknown() && !rulesItem.AccessAll.IsNull() {
				*accessAll = rulesItem.AccessAll.ValueBool()
			} else {
				accessAll = nil
			}
			mesh := new(string)
			if !rulesItem.Mesh.IsUnknown() && !rulesItem.Mesh.IsNull() {
				*mesh = rulesItem.Mesh.ValueString()
			} else {
				mesh = nil
			}
			var typesVar []string
			if rulesItem.Types != nil {
				typesVar = make([]string, 0, len(rulesItem.Types))
				for _, typesItem := range rulesItem.Types {
					typesVar = append(typesVar, typesItem.ValueString())
				}
			}
			rules = append(rules, shared.Rules{
				Access:    access,
				AccessAll: accessAll,
				Mesh:      mesh,
				Types:     typesVar,
			})
		}
	}
	var typeVar string
	typeVar = r.Type.ValueString()

	out := shared.AccessAuditItem{
		Labels: labels,
		Name:   name,
		Rules:  rules,
		Type:   typeVar,
	}

	return &out, diags
}
