// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"github.com/Kong/shared-speakeasy/customtypes/kumalabels"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/kong/terraform-provider-kong-mesh/internal/provider/typeconvert"
	tfTypes "github.com/kong/terraform-provider-kong-mesh/internal/provider/types"
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/operations"
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
)

func (r *MeshExternalServiceResourceModel) RefreshFromSharedMeshExternalServiceCreateOrUpdateSuccessResponse(ctx context.Context, resp *shared.MeshExternalServiceCreateOrUpdateSuccessResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.Warnings = make([]types.String, 0, len(resp.Warnings))
		for _, v := range resp.Warnings {
			r.Warnings = append(r.Warnings, types.StringValue(v))
		}
	}

	return diags
}

func (r *MeshExternalServiceResourceModel) RefreshFromSharedMeshExternalServiceItem(ctx context.Context, resp *shared.MeshExternalServiceItem) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.CreationTime = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.CreationTime))
		r.Kri = types.StringPointerValue(resp.Kri)
		labelsValue, labelsDiags := types.MapValueFrom(ctx, types.StringType, resp.Labels)
		diags.Append(labelsDiags...)
		labelsValuable, labelsDiags := kumalabels.KumaLabelsMapType{MapType: types.MapType{ElemType: types.StringType}}.ValueFromMap(ctx, labelsValue)
		diags.Append(labelsDiags...)
		r.Labels, _ = labelsValuable.(kumalabels.KumaLabelsMapValue)
		r.Mesh = types.StringPointerValue(resp.Mesh)
		r.ModificationTime = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.ModificationTime))
		r.Name = types.StringValue(resp.Name)
		r.Snis = []tfTypes.Snis{}

		for _, snisItem := range resp.Snis {
			var snis tfTypes.Snis

			snis.Port = types.Int32Value(int32(snisItem.Port))
			snis.Sni = types.StringValue(snisItem.Sni)

			r.Snis = append(r.Snis, snis)
		}
		r.Spec = &tfTypes.MeshExternalServiceItemSpec{}
		r.Spec.Endpoints = []tfTypes.Endpoints{}

		for _, endpointsItem := range resp.Spec.Endpoints {
			var endpoints tfTypes.Endpoints

			endpoints.Address = types.StringValue(endpointsItem.Address)
			endpoints.Port = types.Int32Value(int32(endpointsItem.Port))
			endpoints.Priority = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(endpointsItem.Priority))

			r.Spec.Endpoints = append(r.Spec.Endpoints, endpoints)
		}
		if resp.Spec.Extension == nil {
			r.Spec.Extension = nil
		} else {
			r.Spec.Extension = &tfTypes.MeshExternalServiceItemExtension{}
			if resp.Spec.Extension.Config == nil {
				r.Spec.Extension.Config = jsontypes.NewNormalizedNull()
			} else {
				configResult, _ := json.Marshal(resp.Spec.Extension.Config)
				r.Spec.Extension.Config = jsontypes.NewNormalizedValue(string(configResult))
			}
			r.Spec.Extension.Type = types.StringValue(resp.Spec.Extension.Type)
		}
		r.Spec.Match = &tfTypes.Match{}
		r.Spec.Match.Port = types.Int32Value(int32(resp.Spec.Match.Port))
		if resp.Spec.Match.Protocol != nil {
			r.Spec.Match.Protocol = types.StringValue(string(*resp.Spec.Match.Protocol))
		} else {
			r.Spec.Match.Protocol = types.StringNull()
		}
		if resp.Spec.Match.Type != nil {
			r.Spec.Match.Type = types.StringValue(string(*resp.Spec.Match.Type))
		} else {
			r.Spec.Match.Type = types.StringNull()
		}
		if resp.Spec.TLS == nil {
			r.Spec.TLS = nil
		} else {
			r.Spec.TLS = &tfTypes.TLS{}
			r.Spec.TLS.AllowRenegotiation = types.BoolPointerValue(resp.Spec.TLS.AllowRenegotiation)
			r.Spec.TLS.Enabled = types.BoolPointerValue(resp.Spec.TLS.Enabled)
			if resp.Spec.TLS.Verification == nil {
				r.Spec.TLS.Verification = nil
			} else {
				r.Spec.TLS.Verification = &tfTypes.Verification{}
				if resp.Spec.TLS.Verification.CaCert == nil {
					r.Spec.TLS.Verification.CaCert = nil
				} else {
					r.Spec.TLS.Verification.CaCert = &tfTypes.CaCert{}
					if resp.Spec.TLS.Verification.CaCert.EnvVar == nil {
						r.Spec.TLS.Verification.CaCert.EnvVar = nil
					} else {
						r.Spec.TLS.Verification.CaCert.EnvVar = &tfTypes.MeshExternalServiceItemSpecTLSEnvVar{}
						r.Spec.TLS.Verification.CaCert.EnvVar.Name = types.StringValue(resp.Spec.TLS.Verification.CaCert.EnvVar.Name)
					}
					if resp.Spec.TLS.Verification.CaCert.File == nil {
						r.Spec.TLS.Verification.CaCert.File = nil
					} else {
						r.Spec.TLS.Verification.CaCert.File = &tfTypes.MeshExternalServiceItemSpecTLSFile{}
						r.Spec.TLS.Verification.CaCert.File.Path = types.StringValue(resp.Spec.TLS.Verification.CaCert.File.Path)
					}
					if resp.Spec.TLS.Verification.CaCert.InsecureInline == nil {
						r.Spec.TLS.Verification.CaCert.InsecureInline = nil
					} else {
						r.Spec.TLS.Verification.CaCert.InsecureInline = &tfTypes.MeshExternalServiceItemSpecTLSInsecureInline{}
						r.Spec.TLS.Verification.CaCert.InsecureInline.Value = types.StringValue(resp.Spec.TLS.Verification.CaCert.InsecureInline.Value)
					}
					if resp.Spec.TLS.Verification.CaCert.SecretRef == nil {
						r.Spec.TLS.Verification.CaCert.SecretRef = nil
					} else {
						r.Spec.TLS.Verification.CaCert.SecretRef = &tfTypes.MeshExternalServiceItemSpecTLSSecretRef{}
						r.Spec.TLS.Verification.CaCert.SecretRef.Kind = types.StringValue(string(resp.Spec.TLS.Verification.CaCert.SecretRef.Kind))
						r.Spec.TLS.Verification.CaCert.SecretRef.Name = types.StringValue(resp.Spec.TLS.Verification.CaCert.SecretRef.Name)
					}
					r.Spec.TLS.Verification.CaCert.Type = types.StringValue(string(resp.Spec.TLS.Verification.CaCert.Type))
				}
				if resp.Spec.TLS.Verification.ClientCert == nil {
					r.Spec.TLS.Verification.ClientCert = nil
				} else {
					r.Spec.TLS.Verification.ClientCert = &tfTypes.CaCert{}
					if resp.Spec.TLS.Verification.ClientCert.EnvVar == nil {
						r.Spec.TLS.Verification.ClientCert.EnvVar = nil
					} else {
						r.Spec.TLS.Verification.ClientCert.EnvVar = &tfTypes.MeshExternalServiceItemSpecTLSEnvVar{}
						r.Spec.TLS.Verification.ClientCert.EnvVar.Name = types.StringValue(resp.Spec.TLS.Verification.ClientCert.EnvVar.Name)
					}
					if resp.Spec.TLS.Verification.ClientCert.File == nil {
						r.Spec.TLS.Verification.ClientCert.File = nil
					} else {
						r.Spec.TLS.Verification.ClientCert.File = &tfTypes.MeshExternalServiceItemSpecTLSFile{}
						r.Spec.TLS.Verification.ClientCert.File.Path = types.StringValue(resp.Spec.TLS.Verification.ClientCert.File.Path)
					}
					if resp.Spec.TLS.Verification.ClientCert.InsecureInline == nil {
						r.Spec.TLS.Verification.ClientCert.InsecureInline = nil
					} else {
						r.Spec.TLS.Verification.ClientCert.InsecureInline = &tfTypes.MeshExternalServiceItemSpecTLSInsecureInline{}
						r.Spec.TLS.Verification.ClientCert.InsecureInline.Value = types.StringValue(resp.Spec.TLS.Verification.ClientCert.InsecureInline.Value)
					}
					if resp.Spec.TLS.Verification.ClientCert.SecretRef == nil {
						r.Spec.TLS.Verification.ClientCert.SecretRef = nil
					} else {
						r.Spec.TLS.Verification.ClientCert.SecretRef = &tfTypes.MeshExternalServiceItemSpecTLSSecretRef{}
						r.Spec.TLS.Verification.ClientCert.SecretRef.Kind = types.StringValue(string(resp.Spec.TLS.Verification.ClientCert.SecretRef.Kind))
						r.Spec.TLS.Verification.ClientCert.SecretRef.Name = types.StringValue(resp.Spec.TLS.Verification.ClientCert.SecretRef.Name)
					}
					r.Spec.TLS.Verification.ClientCert.Type = types.StringValue(string(resp.Spec.TLS.Verification.ClientCert.Type))
				}
				if resp.Spec.TLS.Verification.ClientKey == nil {
					r.Spec.TLS.Verification.ClientKey = nil
				} else {
					r.Spec.TLS.Verification.ClientKey = &tfTypes.CaCert{}
					if resp.Spec.TLS.Verification.ClientKey.EnvVar == nil {
						r.Spec.TLS.Verification.ClientKey.EnvVar = nil
					} else {
						r.Spec.TLS.Verification.ClientKey.EnvVar = &tfTypes.MeshExternalServiceItemSpecTLSEnvVar{}
						r.Spec.TLS.Verification.ClientKey.EnvVar.Name = types.StringValue(resp.Spec.TLS.Verification.ClientKey.EnvVar.Name)
					}
					if resp.Spec.TLS.Verification.ClientKey.File == nil {
						r.Spec.TLS.Verification.ClientKey.File = nil
					} else {
						r.Spec.TLS.Verification.ClientKey.File = &tfTypes.MeshExternalServiceItemSpecTLSFile{}
						r.Spec.TLS.Verification.ClientKey.File.Path = types.StringValue(resp.Spec.TLS.Verification.ClientKey.File.Path)
					}
					if resp.Spec.TLS.Verification.ClientKey.InsecureInline == nil {
						r.Spec.TLS.Verification.ClientKey.InsecureInline = nil
					} else {
						r.Spec.TLS.Verification.ClientKey.InsecureInline = &tfTypes.MeshExternalServiceItemSpecTLSInsecureInline{}
						r.Spec.TLS.Verification.ClientKey.InsecureInline.Value = types.StringValue(resp.Spec.TLS.Verification.ClientKey.InsecureInline.Value)
					}
					if resp.Spec.TLS.Verification.ClientKey.SecretRef == nil {
						r.Spec.TLS.Verification.ClientKey.SecretRef = nil
					} else {
						r.Spec.TLS.Verification.ClientKey.SecretRef = &tfTypes.MeshExternalServiceItemSpecTLSSecretRef{}
						r.Spec.TLS.Verification.ClientKey.SecretRef.Kind = types.StringValue(string(resp.Spec.TLS.Verification.ClientKey.SecretRef.Kind))
						r.Spec.TLS.Verification.ClientKey.SecretRef.Name = types.StringValue(resp.Spec.TLS.Verification.ClientKey.SecretRef.Name)
					}
					r.Spec.TLS.Verification.ClientKey.Type = types.StringValue(string(resp.Spec.TLS.Verification.ClientKey.Type))
				}
				if resp.Spec.TLS.Verification.Mode != nil {
					r.Spec.TLS.Verification.Mode = types.StringValue(string(*resp.Spec.TLS.Verification.Mode))
				} else {
					r.Spec.TLS.Verification.Mode = types.StringNull()
				}
				r.Spec.TLS.Verification.ServerName = types.StringPointerValue(resp.Spec.TLS.Verification.ServerName)
				r.Spec.TLS.Verification.SubjectAltNames = []tfTypes.SubjectAltNames{}

				for _, subjectAltNamesItem := range resp.Spec.TLS.Verification.SubjectAltNames {
					var subjectAltNames tfTypes.SubjectAltNames

					if subjectAltNamesItem.Type != nil {
						subjectAltNames.Type = types.StringValue(string(*subjectAltNamesItem.Type))
					} else {
						subjectAltNames.Type = types.StringNull()
					}
					subjectAltNames.Value = types.StringValue(subjectAltNamesItem.Value)

					r.Spec.TLS.Verification.SubjectAltNames = append(r.Spec.TLS.Verification.SubjectAltNames, subjectAltNames)
				}
			}
			if resp.Spec.TLS.Version == nil {
				r.Spec.TLS.Version = nil
			} else {
				r.Spec.TLS.Version = &tfTypes.MeshExternalServiceItemVersion{}
				if resp.Spec.TLS.Version.Max != nil {
					r.Spec.TLS.Version.Max = types.StringValue(string(*resp.Spec.TLS.Version.Max))
				} else {
					r.Spec.TLS.Version.Max = types.StringNull()
				}
				if resp.Spec.TLS.Version.Min != nil {
					r.Spec.TLS.Version.Min = types.StringValue(string(*resp.Spec.TLS.Version.Min))
				} else {
					r.Spec.TLS.Version.Min = types.StringNull()
				}
			}
		}
		if resp.Status == nil {
			r.Status = nil
		} else {
			r.Status = &tfTypes.MeshExternalServiceItemStatus{}
			r.Status.Addresses = []tfTypes.Addresses{}

			for _, addressesItem := range resp.Status.Addresses {
				var addresses tfTypes.Addresses

				addresses.Hostname = types.StringPointerValue(addressesItem.Hostname)
				if addressesItem.HostnameGeneratorRef == nil {
					addresses.HostnameGeneratorRef = nil
				} else {
					addresses.HostnameGeneratorRef = &tfTypes.HostnameGeneratorRef{}
					addresses.HostnameGeneratorRef.CoreName = types.StringValue(addressesItem.HostnameGeneratorRef.CoreName)
				}
				addresses.Origin = types.StringPointerValue(addressesItem.Origin)

				r.Status.Addresses = append(r.Status.Addresses, addresses)
			}
			r.Status.HostnameGenerators = []tfTypes.HostnameGenerators{}

			for _, hostnameGeneratorsItem := range resp.Status.HostnameGenerators {
				var hostnameGenerators tfTypes.HostnameGenerators

				hostnameGenerators.Conditions = []tfTypes.Conditions{}

				for _, conditionsItem := range hostnameGeneratorsItem.Conditions {
					var conditions tfTypes.Conditions

					conditions.Message = types.StringValue(conditionsItem.Message)
					conditions.Reason = types.StringValue(conditionsItem.Reason)
					conditions.Status = types.StringValue(string(conditionsItem.Status))
					conditions.Type = types.StringValue(conditionsItem.Type)

					hostnameGenerators.Conditions = append(hostnameGenerators.Conditions, conditions)
				}
				hostnameGenerators.HostnameGeneratorRef = &tfTypes.HostnameGeneratorRef{}
				hostnameGenerators.HostnameGeneratorRef.CoreName = types.StringValue(hostnameGeneratorsItem.HostnameGeneratorRef.CoreName)

				r.Status.HostnameGenerators = append(r.Status.HostnameGenerators, hostnameGenerators)
			}
			if resp.Status.Vip == nil {
				r.Status.Vip = nil
			} else {
				r.Status.Vip = &tfTypes.Vip{}
				r.Status.Vip.IP = types.StringPointerValue(resp.Status.Vip.IP)
			}
		}
		r.Type = types.StringValue(string(resp.Type))
	}

	return diags
}

func (r *MeshExternalServiceResourceModel) ToOperationsDeleteMeshExternalServiceRequest(ctx context.Context) (*operations.DeleteMeshExternalServiceRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var mesh string
	mesh = r.Mesh.ValueString()

	var name string
	name = r.Name.ValueString()

	out := operations.DeleteMeshExternalServiceRequest{
		Mesh: mesh,
		Name: name,
	}

	return &out, diags
}

func (r *MeshExternalServiceResourceModel) ToOperationsGetMeshExternalServiceRequest(ctx context.Context) (*operations.GetMeshExternalServiceRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var mesh string
	mesh = r.Mesh.ValueString()

	var name string
	name = r.Name.ValueString()

	out := operations.GetMeshExternalServiceRequest{
		Mesh: mesh,
		Name: name,
	}

	return &out, diags
}

func (r *MeshExternalServiceResourceModel) ToOperationsPutMeshExternalServiceRequest(ctx context.Context) (*operations.PutMeshExternalServiceRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var mesh string
	mesh = r.Mesh.ValueString()

	var name string
	name = r.Name.ValueString()

	meshExternalServiceItem, meshExternalServiceItemDiags := r.ToSharedMeshExternalServiceItemInput(ctx)
	diags.Append(meshExternalServiceItemDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.PutMeshExternalServiceRequest{
		Mesh:                    mesh,
		Name:                    name,
		MeshExternalServiceItem: *meshExternalServiceItem,
	}

	return &out, diags
}

func (r *MeshExternalServiceResourceModel) ToSharedMeshExternalServiceItemInput(ctx context.Context) (*shared.MeshExternalServiceItemInput, diag.Diagnostics) {
	var diags diag.Diagnostics

	typeVar := shared.MeshExternalServiceItemType(r.Type.ValueString())
	mesh := new(string)
	if !r.Mesh.IsUnknown() && !r.Mesh.IsNull() {
		*mesh = r.Mesh.ValueString()
	} else {
		mesh = nil
	}
	var name string
	name = r.Name.ValueString()

	var labels map[string]string
	if !r.Labels.IsUnknown() && !r.Labels.IsNull() {
		diags.Append(r.Labels.ElementsAs(ctx, &labels, true)...)
	}
	endpoints := make([]shared.Endpoints, 0, len(r.Spec.Endpoints))
	for endpointsIndex := range r.Spec.Endpoints {
		var address string
		address = r.Spec.Endpoints[endpointsIndex].Address.ValueString()

		var port int
		port = int(r.Spec.Endpoints[endpointsIndex].Port.ValueInt32())

		priority := new(int)
		if !r.Spec.Endpoints[endpointsIndex].Priority.IsUnknown() && !r.Spec.Endpoints[endpointsIndex].Priority.IsNull() {
			*priority = int(r.Spec.Endpoints[endpointsIndex].Priority.ValueInt32())
		} else {
			priority = nil
		}
		endpoints = append(endpoints, shared.Endpoints{
			Address:  address,
			Port:     port,
			Priority: priority,
		})
	}
	var extension *shared.MeshExternalServiceItemExtension
	if r.Spec.Extension != nil {
		var config interface{}
		if !r.Spec.Extension.Config.IsUnknown() && !r.Spec.Extension.Config.IsNull() {
			_ = json.Unmarshal([]byte(r.Spec.Extension.Config.ValueString()), &config)
		}
		var typeVar1 string
		typeVar1 = r.Spec.Extension.Type.ValueString()

		extension = &shared.MeshExternalServiceItemExtension{
			Config: config,
			Type:   typeVar1,
		}
	}
	var port1 int
	port1 = int(r.Spec.Match.Port.ValueInt32())

	protocol := new(shared.MeshExternalServiceItemProtocol)
	if !r.Spec.Match.Protocol.IsUnknown() && !r.Spec.Match.Protocol.IsNull() {
		*protocol = shared.MeshExternalServiceItemProtocol(r.Spec.Match.Protocol.ValueString())
	} else {
		protocol = nil
	}
	typeVar2 := new(shared.MeshExternalServiceItemSpecType)
	if !r.Spec.Match.Type.IsUnknown() && !r.Spec.Match.Type.IsNull() {
		*typeVar2 = shared.MeshExternalServiceItemSpecType(r.Spec.Match.Type.ValueString())
	} else {
		typeVar2 = nil
	}
	match := shared.Match{
		Port:     port1,
		Protocol: protocol,
		Type:     typeVar2,
	}
	var tls *shared.TLS
	if r.Spec.TLS != nil {
		allowRenegotiation := new(bool)
		if !r.Spec.TLS.AllowRenegotiation.IsUnknown() && !r.Spec.TLS.AllowRenegotiation.IsNull() {
			*allowRenegotiation = r.Spec.TLS.AllowRenegotiation.ValueBool()
		} else {
			allowRenegotiation = nil
		}
		enabled := new(bool)
		if !r.Spec.TLS.Enabled.IsUnknown() && !r.Spec.TLS.Enabled.IsNull() {
			*enabled = r.Spec.TLS.Enabled.ValueBool()
		} else {
			enabled = nil
		}
		var verification *shared.Verification
		if r.Spec.TLS.Verification != nil {
			var caCert *shared.CaCert
			if r.Spec.TLS.Verification.CaCert != nil {
				var envVar *shared.MeshExternalServiceItemSpecTLSEnvVar
				if r.Spec.TLS.Verification.CaCert.EnvVar != nil {
					var name1 string
					name1 = r.Spec.TLS.Verification.CaCert.EnvVar.Name.ValueString()

					envVar = &shared.MeshExternalServiceItemSpecTLSEnvVar{
						Name: name1,
					}
				}
				var file *shared.MeshExternalServiceItemSpecTLSFile
				if r.Spec.TLS.Verification.CaCert.File != nil {
					var path string
					path = r.Spec.TLS.Verification.CaCert.File.Path.ValueString()

					file = &shared.MeshExternalServiceItemSpecTLSFile{
						Path: path,
					}
				}
				var insecureInline *shared.MeshExternalServiceItemSpecTLSInsecureInline
				if r.Spec.TLS.Verification.CaCert.InsecureInline != nil {
					var value string
					value = r.Spec.TLS.Verification.CaCert.InsecureInline.Value.ValueString()

					insecureInline = &shared.MeshExternalServiceItemSpecTLSInsecureInline{
						Value: value,
					}
				}
				var secretRef *shared.MeshExternalServiceItemSpecTLSSecretRef
				if r.Spec.TLS.Verification.CaCert.SecretRef != nil {
					kind := shared.MeshExternalServiceItemKind(r.Spec.TLS.Verification.CaCert.SecretRef.Kind.ValueString())
					var name2 string
					name2 = r.Spec.TLS.Verification.CaCert.SecretRef.Name.ValueString()

					secretRef = &shared.MeshExternalServiceItemSpecTLSSecretRef{
						Kind: kind,
						Name: name2,
					}
				}
				typeVar3 := shared.MeshExternalServiceItemSpecTLSType(r.Spec.TLS.Verification.CaCert.Type.ValueString())
				caCert = &shared.CaCert{
					EnvVar:         envVar,
					File:           file,
					InsecureInline: insecureInline,
					SecretRef:      secretRef,
					Type:           typeVar3,
				}
			}
			var clientCert *shared.ClientCert
			if r.Spec.TLS.Verification.ClientCert != nil {
				var envVar1 *shared.MeshExternalServiceItemEnvVar
				if r.Spec.TLS.Verification.ClientCert.EnvVar != nil {
					var name3 string
					name3 = r.Spec.TLS.Verification.ClientCert.EnvVar.Name.ValueString()

					envVar1 = &shared.MeshExternalServiceItemEnvVar{
						Name: name3,
					}
				}
				var file1 *shared.MeshExternalServiceItemFile
				if r.Spec.TLS.Verification.ClientCert.File != nil {
					var path1 string
					path1 = r.Spec.TLS.Verification.ClientCert.File.Path.ValueString()

					file1 = &shared.MeshExternalServiceItemFile{
						Path: path1,
					}
				}
				var insecureInline1 *shared.MeshExternalServiceItemInsecureInline
				if r.Spec.TLS.Verification.ClientCert.InsecureInline != nil {
					var value1 string
					value1 = r.Spec.TLS.Verification.ClientCert.InsecureInline.Value.ValueString()

					insecureInline1 = &shared.MeshExternalServiceItemInsecureInline{
						Value: value1,
					}
				}
				var secretRef1 *shared.MeshExternalServiceItemSecretRef
				if r.Spec.TLS.Verification.ClientCert.SecretRef != nil {
					kind1 := shared.MeshExternalServiceItemSpecKind(r.Spec.TLS.Verification.ClientCert.SecretRef.Kind.ValueString())
					var name4 string
					name4 = r.Spec.TLS.Verification.ClientCert.SecretRef.Name.ValueString()

					secretRef1 = &shared.MeshExternalServiceItemSecretRef{
						Kind: kind1,
						Name: name4,
					}
				}
				typeVar4 := shared.MeshExternalServiceItemSpecTLSVerificationType(r.Spec.TLS.Verification.ClientCert.Type.ValueString())
				clientCert = &shared.ClientCert{
					EnvVar:         envVar1,
					File:           file1,
					InsecureInline: insecureInline1,
					SecretRef:      secretRef1,
					Type:           typeVar4,
				}
			}
			var clientKey *shared.ClientKey
			if r.Spec.TLS.Verification.ClientKey != nil {
				var envVar2 *shared.MeshExternalServiceItemSpecEnvVar
				if r.Spec.TLS.Verification.ClientKey.EnvVar != nil {
					var name5 string
					name5 = r.Spec.TLS.Verification.ClientKey.EnvVar.Name.ValueString()

					envVar2 = &shared.MeshExternalServiceItemSpecEnvVar{
						Name: name5,
					}
				}
				var file2 *shared.MeshExternalServiceItemSpecFile
				if r.Spec.TLS.Verification.ClientKey.File != nil {
					var path2 string
					path2 = r.Spec.TLS.Verification.ClientKey.File.Path.ValueString()

					file2 = &shared.MeshExternalServiceItemSpecFile{
						Path: path2,
					}
				}
				var insecureInline2 *shared.MeshExternalServiceItemSpecInsecureInline
				if r.Spec.TLS.Verification.ClientKey.InsecureInline != nil {
					var value2 string
					value2 = r.Spec.TLS.Verification.ClientKey.InsecureInline.Value.ValueString()

					insecureInline2 = &shared.MeshExternalServiceItemSpecInsecureInline{
						Value: value2,
					}
				}
				var secretRef2 *shared.MeshExternalServiceItemSpecSecretRef
				if r.Spec.TLS.Verification.ClientKey.SecretRef != nil {
					kind2 := shared.MeshExternalServiceItemSpecTLSKind(r.Spec.TLS.Verification.ClientKey.SecretRef.Kind.ValueString())
					var name6 string
					name6 = r.Spec.TLS.Verification.ClientKey.SecretRef.Name.ValueString()

					secretRef2 = &shared.MeshExternalServiceItemSpecSecretRef{
						Kind: kind2,
						Name: name6,
					}
				}
				typeVar5 := shared.MeshExternalServiceItemSpecTLSVerificationClientKeyType(r.Spec.TLS.Verification.ClientKey.Type.ValueString())
				clientKey = &shared.ClientKey{
					EnvVar:         envVar2,
					File:           file2,
					InsecureInline: insecureInline2,
					SecretRef:      secretRef2,
					Type:           typeVar5,
				}
			}
			mode := new(shared.MeshExternalServiceItemMode)
			if !r.Spec.TLS.Verification.Mode.IsUnknown() && !r.Spec.TLS.Verification.Mode.IsNull() {
				*mode = shared.MeshExternalServiceItemMode(r.Spec.TLS.Verification.Mode.ValueString())
			} else {
				mode = nil
			}
			serverName := new(string)
			if !r.Spec.TLS.Verification.ServerName.IsUnknown() && !r.Spec.TLS.Verification.ServerName.IsNull() {
				*serverName = r.Spec.TLS.Verification.ServerName.ValueString()
			} else {
				serverName = nil
			}
			subjectAltNames := make([]shared.SubjectAltNames, 0, len(r.Spec.TLS.Verification.SubjectAltNames))
			for subjectAltNamesIndex := range r.Spec.TLS.Verification.SubjectAltNames {
				type1 := new(shared.MeshExternalServiceItemSpecTLSVerificationSubjectAltNamesType)
				if !r.Spec.TLS.Verification.SubjectAltNames[subjectAltNamesIndex].Type.IsUnknown() && !r.Spec.TLS.Verification.SubjectAltNames[subjectAltNamesIndex].Type.IsNull() {
					*type1 = shared.MeshExternalServiceItemSpecTLSVerificationSubjectAltNamesType(r.Spec.TLS.Verification.SubjectAltNames[subjectAltNamesIndex].Type.ValueString())
				} else {
					type1 = nil
				}
				var value3 string
				value3 = r.Spec.TLS.Verification.SubjectAltNames[subjectAltNamesIndex].Value.ValueString()

				subjectAltNames = append(subjectAltNames, shared.SubjectAltNames{
					Type:  type1,
					Value: value3,
				})
			}
			verification = &shared.Verification{
				CaCert:          caCert,
				ClientCert:      clientCert,
				ClientKey:       clientKey,
				Mode:            mode,
				ServerName:      serverName,
				SubjectAltNames: subjectAltNames,
			}
		}
		var version *shared.MeshExternalServiceItemVersion
		if r.Spec.TLS.Version != nil {
			max := new(shared.Max)
			if !r.Spec.TLS.Version.Max.IsUnknown() && !r.Spec.TLS.Version.Max.IsNull() {
				*max = shared.Max(r.Spec.TLS.Version.Max.ValueString())
			} else {
				max = nil
			}
			min := new(shared.Min)
			if !r.Spec.TLS.Version.Min.IsUnknown() && !r.Spec.TLS.Version.Min.IsNull() {
				*min = shared.Min(r.Spec.TLS.Version.Min.ValueString())
			} else {
				min = nil
			}
			version = &shared.MeshExternalServiceItemVersion{
				Max: max,
				Min: min,
			}
		}
		tls = &shared.TLS{
			AllowRenegotiation: allowRenegotiation,
			Enabled:            enabled,
			Verification:       verification,
			Version:            version,
		}
	}
	spec := shared.MeshExternalServiceItemSpec{
		Endpoints: endpoints,
		Extension: extension,
		Match:     match,
		TLS:       tls,
	}
	out := shared.MeshExternalServiceItemInput{
		Type:   typeVar,
		Mesh:   mesh,
		Name:   name,
		Labels: labels,
		Spec:   spec,
	}

	return &out, diags
}
