// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/kong/terraform-provider-kong-mesh/internal/provider/typeconvert"
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/operations"
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
)

func (r *MeshGlobalSecretAliasResourceModel) RefreshFromSharedGlobalSecretCreateOrUpdateSuccessResponse(ctx context.Context, resp *shared.GlobalSecretCreateOrUpdateSuccessResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.Warnings = make([]types.String, 0, len(resp.Warnings))
		for _, v := range resp.Warnings {
			r.Warnings = append(r.Warnings, types.StringValue(v))
		}
	}

	return diags
}

func (r *MeshGlobalSecretAliasResourceModel) RefreshFromSharedGlobalSecretItem(ctx context.Context, resp *shared.GlobalSecretItem) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.CreationTime = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.CreationTime))
		r.Data = types.StringPointerValue(resp.Data)
		if len(resp.Labels) > 0 {
			r.Labels = make(map[string]types.String, len(resp.Labels))
			for key, value := range resp.Labels {
				r.Labels[key] = types.StringValue(value)
			}
		}
		r.ModificationTime = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.ModificationTime))
		r.Name = types.StringValue(resp.Name)
		r.Type = types.StringValue(resp.Type)
	}

	return diags
}

func (r *MeshGlobalSecretAliasResourceModel) ToOperationsDeleteGlobalSecretAliasRequest(ctx context.Context) (*operations.DeleteGlobalSecretAliasRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var name string
	name = r.Name.ValueString()

	out := operations.DeleteGlobalSecretAliasRequest{
		Name: name,
	}

	return &out, diags
}

func (r *MeshGlobalSecretAliasResourceModel) ToOperationsGetGlobalSecretAliasRequest(ctx context.Context) (*operations.GetGlobalSecretAliasRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var name string
	name = r.Name.ValueString()

	out := operations.GetGlobalSecretAliasRequest{
		Name: name,
	}

	return &out, diags
}

func (r *MeshGlobalSecretAliasResourceModel) ToOperationsPutGlobalSecretAliasRequest(ctx context.Context) (*operations.PutGlobalSecretAliasRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var name string
	name = r.Name.ValueString()

	globalSecretItem, globalSecretItemDiags := r.ToSharedGlobalSecretItemInput(ctx)
	diags.Append(globalSecretItemDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.PutGlobalSecretAliasRequest{
		Name:             name,
		GlobalSecretItem: *globalSecretItem,
	}

	return &out, diags
}

func (r *MeshGlobalSecretAliasResourceModel) ToSharedGlobalSecretItemInput(ctx context.Context) (*shared.GlobalSecretItemInput, diag.Diagnostics) {
	var diags diag.Diagnostics

	var typeVar string
	typeVar = r.Type.ValueString()

	var name string
	name = r.Name.ValueString()

	labels := make(map[string]string)
	for labelsKey := range r.Labels {
		var labelsInst string
		labelsInst = r.Labels[labelsKey].ValueString()

		labels[labelsKey] = labelsInst
	}
	data := new(string)
	if !r.Data.IsUnknown() && !r.Data.IsNull() {
		*data = r.Data.ValueString()
	} else {
		data = nil
	}
	out := shared.GlobalSecretItemInput{
		Type:   typeVar,
		Name:   name,
		Labels: labels,
		Data:   data,
	}

	return &out, diags
}
