// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/kong/terraform-provider-kong-mesh/internal/provider/typeconvert"
	tfTypes "github.com/kong/terraform-provider-kong-mesh/internal/provider/types"
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/operations"
	"github.com/kong/terraform-provider-kong-mesh/internal/sdk/models/shared"
)

func (r *MeshAccessRoleResourceModel) RefreshFromSharedAccessRoleCreateOrUpdateSuccessResponse(ctx context.Context, resp *shared.AccessRoleCreateOrUpdateSuccessResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.Warnings = make([]types.String, 0, len(resp.Warnings))
		for _, v := range resp.Warnings {
			r.Warnings = append(r.Warnings, types.StringValue(v))
		}
	}

	return diags
}

func (r *MeshAccessRoleResourceModel) RefreshFromSharedAccessRoleItem(ctx context.Context, resp *shared.AccessRoleItem) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.CreationTime = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.CreationTime))
		r.Kri = types.StringPointerValue(resp.Kri)
		if len(resp.Labels) > 0 {
			r.Labels = make(map[string]types.String, len(resp.Labels))
			for key, value := range resp.Labels {
				r.Labels[key] = types.StringValue(value)
			}
		}
		r.ModificationTime = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.ModificationTime))
		r.Name = types.StringValue(resp.Name)
		if resp.Rules != nil {
			r.Rules = []tfTypes.AccessRoleItemRules{}

			for _, rulesItem := range resp.Rules {
				var rules tfTypes.AccessRoleItemRules

				if rulesItem.Access != nil {
					rules.Access = make([]types.String, 0, len(rulesItem.Access))
					for _, v := range rulesItem.Access {
						rules.Access = append(rules.Access, types.StringValue(string(v)))
					}
				} else {
					rules.Access = nil
				}
				rules.Mesh = types.StringPointerValue(rulesItem.Mesh)
				if rulesItem.Names != nil {
					rules.Names = make([]types.String, 0, len(rulesItem.Names))
					for _, v := range rulesItem.Names {
						rules.Names = append(rules.Names, types.StringValue(v))
					}
				} else {
					rules.Names = nil
				}
				if rulesItem.Types != nil {
					rules.Types = make([]types.String, 0, len(rulesItem.Types))
					for _, v := range rulesItem.Types {
						rules.Types = append(rules.Types, types.StringValue(v))
					}
				} else {
					rules.Types = nil
				}
				if rulesItem.When != nil {
					rules.When = []tfTypes.When{}

					for _, whenItem := range rulesItem.When {
						var when tfTypes.When

						if whenItem.Destinations == nil {
							when.Destinations = nil
						} else {
							when.Destinations = &tfTypes.Destinations{}
							if len(whenItem.Destinations.Match) > 0 {
								when.Destinations.Match = make(map[string]types.String, len(whenItem.Destinations.Match))
								for key1, value1 := range whenItem.Destinations.Match {
									when.Destinations.Match[key1] = types.StringValue(value1)
								}
							}
						}
						if whenItem.DpToken == nil {
							when.DpToken = nil
						} else {
							when.DpToken = &tfTypes.DpToken{}
							if whenItem.DpToken.Tags != nil {
								when.DpToken.Tags = []tfTypes.AccessRoleItemTags{}

								for _, tagsItem := range whenItem.DpToken.Tags {
									var tags tfTypes.AccessRoleItemTags

									tags.Name = types.StringPointerValue(tagsItem.Name)
									tags.Value = types.StringPointerValue(tagsItem.Value)

									when.DpToken.Tags = append(when.DpToken.Tags, tags)
								}
							} else {
								when.DpToken.Tags = nil
							}
						}
						if whenItem.From == nil {
							when.From = nil
						} else {
							when.From = &tfTypes.From{}
							if whenItem.From.TargetRef == nil {
								when.From.TargetRef = nil
							} else {
								when.From.TargetRef = &tfTypes.AccessRoleItemRulesTargetRef{}
								when.From.TargetRef.Kind = types.StringPointerValue(whenItem.From.TargetRef.Kind)
								if len(whenItem.From.TargetRef.Labels) > 0 {
									when.From.TargetRef.Labels = make(map[string]types.String, len(whenItem.From.TargetRef.Labels))
									for key2, value2 := range whenItem.From.TargetRef.Labels {
										when.From.TargetRef.Labels[key2] = types.StringValue(value2)
									}
								}
								when.From.TargetRef.Name = types.StringPointerValue(whenItem.From.TargetRef.Name)
							}
						}
						if whenItem.Selectors == nil {
							when.Selectors = nil
						} else {
							when.Selectors = &tfTypes.Destinations{}
							if len(whenItem.Selectors.Match) > 0 {
								when.Selectors.Match = make(map[string]types.String, len(whenItem.Selectors.Match))
								for key3, value3 := range whenItem.Selectors.Match {
									when.Selectors.Match[key3] = types.StringValue(value3)
								}
							}
						}
						if whenItem.Sources == nil {
							when.Sources = nil
						} else {
							when.Sources = &tfTypes.Destinations{}
							if len(whenItem.Sources.Match) > 0 {
								when.Sources.Match = make(map[string]types.String, len(whenItem.Sources.Match))
								for key4, value4 := range whenItem.Sources.Match {
									when.Sources.Match[key4] = types.StringValue(value4)
								}
							}
						}
						if whenItem.TargetRef == nil {
							when.TargetRef = nil
						} else {
							when.TargetRef = &tfTypes.AccessRoleItemRulesTargetRef{}
							when.TargetRef.Kind = types.StringPointerValue(whenItem.TargetRef.Kind)
							if len(whenItem.TargetRef.Labels) > 0 {
								when.TargetRef.Labels = make(map[string]types.String, len(whenItem.TargetRef.Labels))
								for key5, value5 := range whenItem.TargetRef.Labels {
									when.TargetRef.Labels[key5] = types.StringValue(value5)
								}
							}
							when.TargetRef.Name = types.StringPointerValue(whenItem.TargetRef.Name)
						}
						if whenItem.To == nil {
							when.To = nil
						} else {
							when.To = &tfTypes.From{}
							if whenItem.To.TargetRef == nil {
								when.To.TargetRef = nil
							} else {
								when.To.TargetRef = &tfTypes.AccessRoleItemRulesTargetRef{}
								when.To.TargetRef.Kind = types.StringPointerValue(whenItem.To.TargetRef.Kind)
								if len(whenItem.To.TargetRef.Labels) > 0 {
									when.To.TargetRef.Labels = make(map[string]types.String, len(whenItem.To.TargetRef.Labels))
									for key6, value6 := range whenItem.To.TargetRef.Labels {
										when.To.TargetRef.Labels[key6] = types.StringValue(value6)
									}
								}
								when.To.TargetRef.Name = types.StringPointerValue(whenItem.To.TargetRef.Name)
							}
						}

						rules.When = append(rules.When, when)
					}
				} else {
					rules.When = nil
				}

				r.Rules = append(r.Rules, rules)
			}
		} else {
			r.Rules = nil
		}
		r.Type = types.StringValue(resp.Type)
	}

	return diags
}

func (r *MeshAccessRoleResourceModel) ToOperationsDeleteAccessRoleRequest(ctx context.Context) (*operations.DeleteAccessRoleRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var name string
	name = r.Name.ValueString()

	out := operations.DeleteAccessRoleRequest{
		Name: name,
	}

	return &out, diags
}

func (r *MeshAccessRoleResourceModel) ToOperationsGetAccessRoleRequest(ctx context.Context) (*operations.GetAccessRoleRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var name string
	name = r.Name.ValueString()

	out := operations.GetAccessRoleRequest{
		Name: name,
	}

	return &out, diags
}

func (r *MeshAccessRoleResourceModel) ToOperationsPutAccessRoleRequest(ctx context.Context) (*operations.PutAccessRoleRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var name string
	name = r.Name.ValueString()

	accessRoleItem, accessRoleItemDiags := r.ToSharedAccessRoleItemInput(ctx)
	diags.Append(accessRoleItemDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.PutAccessRoleRequest{
		Name:           name,
		AccessRoleItem: *accessRoleItem,
	}

	return &out, diags
}

func (r *MeshAccessRoleResourceModel) ToSharedAccessRoleItemInput(ctx context.Context) (*shared.AccessRoleItemInput, diag.Diagnostics) {
	var diags diag.Diagnostics

	labels := make(map[string]string)
	for labelsKey := range r.Labels {
		var labelsInst string
		labelsInst = r.Labels[labelsKey].ValueString()

		labels[labelsKey] = labelsInst
	}
	var name string
	name = r.Name.ValueString()

	var rules []shared.AccessRoleItemRules
	if r.Rules != nil {
		rules = make([]shared.AccessRoleItemRules, 0, len(r.Rules))
		for rulesIndex := range r.Rules {
			var access []shared.AccessRoleItemAccess
			if r.Rules[rulesIndex].Access != nil {
				access = make([]shared.AccessRoleItemAccess, 0, len(r.Rules[rulesIndex].Access))
				for _, accessItem := range r.Rules[rulesIndex].Access {
					access = append(access, shared.AccessRoleItemAccess(accessItem.ValueString()))
				}
			}
			mesh := new(string)
			if !r.Rules[rulesIndex].Mesh.IsUnknown() && !r.Rules[rulesIndex].Mesh.IsNull() {
				*mesh = r.Rules[rulesIndex].Mesh.ValueString()
			} else {
				mesh = nil
			}
			var names []string
			if r.Rules[rulesIndex].Names != nil {
				names = make([]string, 0, len(r.Rules[rulesIndex].Names))
				for namesIndex := range r.Rules[rulesIndex].Names {
					names = append(names, r.Rules[rulesIndex].Names[namesIndex].ValueString())
				}
			}
			var typesVar []string
			if r.Rules[rulesIndex].Types != nil {
				typesVar = make([]string, 0, len(r.Rules[rulesIndex].Types))
				for typesIndex := range r.Rules[rulesIndex].Types {
					typesVar = append(typesVar, r.Rules[rulesIndex].Types[typesIndex].ValueString())
				}
			}
			var when []shared.When
			if r.Rules[rulesIndex].When != nil {
				when = make([]shared.When, 0, len(r.Rules[rulesIndex].When))
				for whenIndex := range r.Rules[rulesIndex].When {
					var destinations *shared.Destinations
					if r.Rules[rulesIndex].When[whenIndex].Destinations != nil {
						match := make(map[string]string)
						for matchKey := range r.Rules[rulesIndex].When[whenIndex].Destinations.Match {
							var matchInst string
							matchInst = r.Rules[rulesIndex].When[whenIndex].Destinations.Match[matchKey].ValueString()

							match[matchKey] = matchInst
						}
						destinations = &shared.Destinations{
							Match: match,
						}
					}
					var dpToken *shared.DpToken
					if r.Rules[rulesIndex].When[whenIndex].DpToken != nil {
						var tags []shared.AccessRoleItemTags
						if r.Rules[rulesIndex].When[whenIndex].DpToken.Tags != nil {
							tags = make([]shared.AccessRoleItemTags, 0, len(r.Rules[rulesIndex].When[whenIndex].DpToken.Tags))
							for tagsIndex := range r.Rules[rulesIndex].When[whenIndex].DpToken.Tags {
								name1 := new(string)
								if !r.Rules[rulesIndex].When[whenIndex].DpToken.Tags[tagsIndex].Name.IsUnknown() && !r.Rules[rulesIndex].When[whenIndex].DpToken.Tags[tagsIndex].Name.IsNull() {
									*name1 = r.Rules[rulesIndex].When[whenIndex].DpToken.Tags[tagsIndex].Name.ValueString()
								} else {
									name1 = nil
								}
								value := new(string)
								if !r.Rules[rulesIndex].When[whenIndex].DpToken.Tags[tagsIndex].Value.IsUnknown() && !r.Rules[rulesIndex].When[whenIndex].DpToken.Tags[tagsIndex].Value.IsNull() {
									*value = r.Rules[rulesIndex].When[whenIndex].DpToken.Tags[tagsIndex].Value.ValueString()
								} else {
									value = nil
								}
								tags = append(tags, shared.AccessRoleItemTags{
									Name:  name1,
									Value: value,
								})
							}
						}
						dpToken = &shared.DpToken{
							Tags: tags,
						}
					}
					var from *shared.From
					if r.Rules[rulesIndex].When[whenIndex].From != nil {
						var targetRef *shared.AccessRoleItemRulesTargetRef
						if r.Rules[rulesIndex].When[whenIndex].From.TargetRef != nil {
							kind := new(string)
							if !r.Rules[rulesIndex].When[whenIndex].From.TargetRef.Kind.IsUnknown() && !r.Rules[rulesIndex].When[whenIndex].From.TargetRef.Kind.IsNull() {
								*kind = r.Rules[rulesIndex].When[whenIndex].From.TargetRef.Kind.ValueString()
							} else {
								kind = nil
							}
							labels1 := make(map[string]string)
							for labelsKey1 := range r.Rules[rulesIndex].When[whenIndex].From.TargetRef.Labels {
								var labelsInst1 string
								labelsInst1 = r.Rules[rulesIndex].When[whenIndex].From.TargetRef.Labels[labelsKey1].ValueString()

								labels1[labelsKey1] = labelsInst1
							}
							name2 := new(string)
							if !r.Rules[rulesIndex].When[whenIndex].From.TargetRef.Name.IsUnknown() && !r.Rules[rulesIndex].When[whenIndex].From.TargetRef.Name.IsNull() {
								*name2 = r.Rules[rulesIndex].When[whenIndex].From.TargetRef.Name.ValueString()
							} else {
								name2 = nil
							}
							targetRef = &shared.AccessRoleItemRulesTargetRef{
								Kind:   kind,
								Labels: labels1,
								Name:   name2,
							}
						}
						from = &shared.From{
							TargetRef: targetRef,
						}
					}
					var selectors *shared.Selectors
					if r.Rules[rulesIndex].When[whenIndex].Selectors != nil {
						match1 := make(map[string]string)
						for matchKey1 := range r.Rules[rulesIndex].When[whenIndex].Selectors.Match {
							var matchInst1 string
							matchInst1 = r.Rules[rulesIndex].When[whenIndex].Selectors.Match[matchKey1].ValueString()

							match1[matchKey1] = matchInst1
						}
						selectors = &shared.Selectors{
							Match: match1,
						}
					}
					var sources *shared.Sources
					if r.Rules[rulesIndex].When[whenIndex].Sources != nil {
						match2 := make(map[string]string)
						for matchKey2 := range r.Rules[rulesIndex].When[whenIndex].Sources.Match {
							var matchInst2 string
							matchInst2 = r.Rules[rulesIndex].When[whenIndex].Sources.Match[matchKey2].ValueString()

							match2[matchKey2] = matchInst2
						}
						sources = &shared.Sources{
							Match: match2,
						}
					}
					var targetRef1 *shared.AccessRoleItemTargetRef
					if r.Rules[rulesIndex].When[whenIndex].TargetRef != nil {
						kind1 := new(string)
						if !r.Rules[rulesIndex].When[whenIndex].TargetRef.Kind.IsUnknown() && !r.Rules[rulesIndex].When[whenIndex].TargetRef.Kind.IsNull() {
							*kind1 = r.Rules[rulesIndex].When[whenIndex].TargetRef.Kind.ValueString()
						} else {
							kind1 = nil
						}
						labels2 := make(map[string]string)
						for labelsKey2 := range r.Rules[rulesIndex].When[whenIndex].TargetRef.Labels {
							var labelsInst2 string
							labelsInst2 = r.Rules[rulesIndex].When[whenIndex].TargetRef.Labels[labelsKey2].ValueString()

							labels2[labelsKey2] = labelsInst2
						}
						name3 := new(string)
						if !r.Rules[rulesIndex].When[whenIndex].TargetRef.Name.IsUnknown() && !r.Rules[rulesIndex].When[whenIndex].TargetRef.Name.IsNull() {
							*name3 = r.Rules[rulesIndex].When[whenIndex].TargetRef.Name.ValueString()
						} else {
							name3 = nil
						}
						targetRef1 = &shared.AccessRoleItemTargetRef{
							Kind:   kind1,
							Labels: labels2,
							Name:   name3,
						}
					}
					var to *shared.AccessRoleItemTo
					if r.Rules[rulesIndex].When[whenIndex].To != nil {
						var targetRef2 *shared.AccessRoleItemRulesWhenTargetRef
						if r.Rules[rulesIndex].When[whenIndex].To.TargetRef != nil {
							kind2 := new(string)
							if !r.Rules[rulesIndex].When[whenIndex].To.TargetRef.Kind.IsUnknown() && !r.Rules[rulesIndex].When[whenIndex].To.TargetRef.Kind.IsNull() {
								*kind2 = r.Rules[rulesIndex].When[whenIndex].To.TargetRef.Kind.ValueString()
							} else {
								kind2 = nil
							}
							labels3 := make(map[string]string)
							for labelsKey3 := range r.Rules[rulesIndex].When[whenIndex].To.TargetRef.Labels {
								var labelsInst3 string
								labelsInst3 = r.Rules[rulesIndex].When[whenIndex].To.TargetRef.Labels[labelsKey3].ValueString()

								labels3[labelsKey3] = labelsInst3
							}
							name4 := new(string)
							if !r.Rules[rulesIndex].When[whenIndex].To.TargetRef.Name.IsUnknown() && !r.Rules[rulesIndex].When[whenIndex].To.TargetRef.Name.IsNull() {
								*name4 = r.Rules[rulesIndex].When[whenIndex].To.TargetRef.Name.ValueString()
							} else {
								name4 = nil
							}
							targetRef2 = &shared.AccessRoleItemRulesWhenTargetRef{
								Kind:   kind2,
								Labels: labels3,
								Name:   name4,
							}
						}
						to = &shared.AccessRoleItemTo{
							TargetRef: targetRef2,
						}
					}
					when = append(when, shared.When{
						Destinations: destinations,
						DpToken:      dpToken,
						From:         from,
						Selectors:    selectors,
						Sources:      sources,
						TargetRef:    targetRef1,
						To:           to,
					})
				}
			}
			rules = append(rules, shared.AccessRoleItemRules{
				Access: access,
				Mesh:   mesh,
				Names:  names,
				Types:  typesVar,
				When:   when,
			})
		}
	}
	var typeVar string
	typeVar = r.Type.ValueString()

	out := shared.AccessRoleItemInput{
		Labels: labels,
		Name:   name,
		Rules:  rules,
		Type:   typeVar,
	}

	return &out, diags
}
