// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type BackendsFormat struct {
	One *Format1 `queryParam:"inline" tfsdk:"one"`
	Two *Format1 `queryParam:"inline" tfsdk:"two"`
}
