// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type Cert struct {
	DataSourceFile         *DataSourceFile         `queryParam:"inline" tfsdk:"data_source_file" tfPlanOnly:"true"`
	DataSourceInline       *DataSourceInline       `queryParam:"inline" tfsdk:"data_source_inline" tfPlanOnly:"true"`
	DataSourceInlineString *DataSourceInlineString `queryParam:"inline" tfsdk:"data_source_inline_string" tfPlanOnly:"true"`
	DataSourceSecret       *DataSourceSecret       `queryParam:"inline" tfsdk:"data_source_secret" tfPlanOnly:"true"`
}
