// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type DataSourceFile struct {
	File types.String `tfsdk:"file"`
	Type types.String `tfsdk:"type"`
}
