// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type Delay struct {
	Percentage *StandardDeviationFactor `tfsdk:"percentage"`
	Value      types.String             `tfsdk:"value"`
}
