// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type Extension struct {
	Other   *Other `queryParam:"inline" tfsdk:"other"`
	Route53 *Other `queryParam:"inline" tfsdk:"route53"`
}
