// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type MeshHTTPRouteItemFiltersSpecToRulesURLRewrite struct {
	HostToBackendHostname types.Bool                                                  `tfsdk:"host_to_backend_hostname"`
	Hostname              types.String                                                `tfsdk:"hostname"`
	Path                  *MeshHTTPRouteItemFiltersSpecToRulesDefaultBackendRefs1Path `tfsdk:"path"`
}
