// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type MeshTraceItemBackends struct {
	One   *Backends1 `queryParam:"inline" tfsdk:"one"`
	Two   *Backends1 `queryParam:"inline" tfsdk:"two"`
	Three *Backends1 `queryParam:"inline" tfsdk:"three"`
}
