// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type MeshHTTPRouteItemRequestMirror struct {
	BackendRef *MeshHTTPRouteItemSpecBackendRef `tfsdk:"backend_ref"`
	Percentage *StandardDeviationFactor         `tfsdk:"percentage"`
}
