// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type MeshHTTPRouteItemDefault struct {
	BackendRefs []BackendRefs              `tfsdk:"backend_refs"`
	Filters     []MeshHTTPRouteItemFilters `tfsdk:"filters"`
}
