// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type MeshAccessLogItemSpecBackends struct {
	One   *MeshAccessLogItemBackends1 `queryParam:"inline" tfsdk:"one"`
	Two   *MeshAccessLogItemBackends1 `queryParam:"inline" tfsdk:"two"`
	Three *MeshAccessLogItemBackends1 `queryParam:"inline" tfsdk:"three"`
}
