// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type MeshHTTPRouteItemFiltersSpecToRulesDefaultBackendRef struct {
	Kind        types.String            `tfsdk:"kind"`
	Labels      map[string]types.String `tfsdk:"labels"`
	Port        types.Int32             `tfsdk:"port"`
	SectionName types.String            `tfsdk:"section_name"`
	Weight      types.Int64             `tfsdk:"weight"`
}
