// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type MeshHTTPRouteItemFilters1 struct {
	RequestHeaderModifier  *MeshHTTPRouteItemFiltersSpecToRulesRequestHeaderModifier `tfsdk:"request_header_modifier"`
	RequestMirror          *MeshHTTPRouteItemFiltersSpecToRulesRequestMirror         `tfsdk:"request_mirror"`
	RequestRedirect        *MeshHTTPRouteItemFiltersSpecToRulesRequestRedirect       `tfsdk:"request_redirect"`
	ResponseHeaderModifier *MeshHTTPRouteItemFiltersSpecToRulesRequestHeaderModifier `tfsdk:"response_header_modifier"`
	Type                   types.String                                              `tfsdk:"type"`
	URLRewrite             *MeshHTTPRouteItemFiltersSpecToRulesURLRewrite            `tfsdk:"url_rewrite"`
}
