// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type MeshHTTPRouteItemRequestRedirect struct {
	Hostname   types.String                      `tfsdk:"hostname"`
	Path       *MeshHTTPRouteItemSpecToRulesPath `tfsdk:"path"`
	Port       types.Int32                       `tfsdk:"port"`
	Scheme     types.String                      `tfsdk:"scheme"`
	StatusCode types.Int64                       `tfsdk:"status_code"`
}
