// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type MeshHTTPRouteItemFilters struct {
	One   *MeshHTTPRouteItemFilters1 `queryParam:"inline" tfsdk:"one"`
	Two   *MeshHTTPRouteItemFilters1 `queryParam:"inline" tfsdk:"two"`
	Three *MeshHTTPRouteItemFilters1 `queryParam:"inline" tfsdk:"three"`
	Four  *MeshHTTPRouteItemFilters1 `queryParam:"inline" tfsdk:"four"`
	Five  *MeshHTTPRouteItemFilters1 `queryParam:"inline" tfsdk:"five"`
}
