// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type RequestHeadersToAdd struct {
	Add []MeshHTTPRouteItemFiltersSpecToRulesDefaultBackendRefs1Add `tfsdk:"add"`
	Set []MeshHTTPRouteItemFiltersSpecToRulesDefaultBackendRefs1Add `tfsdk:"set"`
}
