// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type Sampling struct {
	Client  *StandardDeviationFactor `tfsdk:"client"`
	Overall *StandardDeviationFactor `tfsdk:"overall"`
	Random  *StandardDeviationFactor `tfsdk:"random"`
}
