// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type TargetRef struct {
	Kind        types.String            `tfsdk:"kind"`
	Labels      map[string]types.String `tfsdk:"labels"`
	SectionName types.String            `tfsdk:"section_name"`
}
